import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { HubFooter, HubHeader } from "@/components/HubHeader";
import { Breadcrumbs, ConsultationCta, JsonLd } from "@/components/SeoBlocks";
import { getProvince, provinces, services, siteUrl } from "@/lib/site-data";
type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return provinces.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const p = getProvince((await params).slug); if (!p) return {}; return { title: `จดบริษัทและบริการธุรกิจใน${p.name}`, description: `บริการจดทะเบียนบริษัท บัญชี ภาษี ประกันสังคม และเปลี่ยนแปลงบริษัทสำหรับผู้ประกอบการใน${p.name} ปรึกษาและส่งข้อมูลออนไลน์`, alternates: { canonical: `/areas/${p.slug}` }, openGraph: { title: `บริการผู้ประกอบการใน${p.name} | ตั้งต้น`, description: `เริ่มและดูแลธุรกิจใน${p.name}กับทีมทะเบียน บัญชี และภาษี`, images: ["/og.png"] } }; }
export default async function AreaPage({ params }: Props) { const province = getProvince((await params).slug); if (!province) notFound(); const popular = services.filter((s) => ["register-company", "vat-registration", "monthly-accounting", "social-security", "change-address", "trademark"].includes(s.slug)); const areaFaqs = [{ q: `อยู่${province.name} จดบริษัทออนไลน์ได้ไหม?`, a: `ได้ ขั้นตอนปรึกษา ส่งข้อมูล ตรวจร่าง และติดตามสถานะทำออนไลน์ได้เป็นส่วนใหญ่ หากมีเอกสารที่ต้องใช้ต้นฉบับหรือการยืนยันในพื้นที่ ผู้ดูแลจะแจ้งก่อนเริ่ม` }, { q: `ใช้ที่อยู่ใน${province.name}เป็นสำนักงานใหญ่ต้องเตรียมอะไร?`, a: "โดยทั่วไปควรมีหลักฐานสิทธิใช้สถานที่ ข้อมูลเจ้าของหรือผู้ให้เช่า แผนที่ และภาพถ่ายตามงานที่เกี่ยวข้อง รวมถึงตรวจข้อจำกัดของอาคารหรือโครงการ" }, { q: "ต้องเดินทางไปกรุงเทพฯ หรือไม่?", a: "ไม่จำเป็นสำหรับงานส่วนใหญ่ ทีมงานออกแบบกระบวนการทางไกลและจัดส่งเอกสาร หากขั้นตอนใดต้องพบเจ้าหน้าที่หรือยืนยันตัวตนจะนัดหมายให้เหมาะกับพื้นที่" }]; const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "ProfessionalService", name: `บริการจดทะเบียนและดูแลธุรกิจใน${province.name}`, areaServed: { "@type": "AdministrativeArea", name: province.name }, provider: { "@type": "Organization", name: "ตั้งต้น" }, url: `${siteUrl}/areas/${province.slug}` }, { "@type": "FAQPage", mainEntity: areaFaqs.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) }] };
  return <><HubHeader /><main className="inner-main"><JsonLd data={schema} /><section className="area-detail-hero"><div className="container"><Breadcrumbs items={[{ label: "หน้าหลัก", href: "/" }, { label: "บริการทั่วไทย", href: "/areas" }, { label: province.name }]} /><p className="eyebrow"><span /> {province.region}</p><h1>จดบริษัทและดูแลธุรกิจ<br />ใน{province.name}</h1><p>ปรึกษา ส่งข้อมูล ตรวจเอกสาร และติดตามงานกับทีมเดียว ลดการเดินทาง พร้อมเชื่อมงานทะเบียน บัญชี ภาษี และใบอนุญาตให้เป็นแผนเดียวกัน</p><Link className="button button-primary" href="/#contact">รับเช็กลิสต์สำหรับ{province.name} <span aria-hidden="true">↗</span></Link></div></section>
    <section className="area-content"><div className="container"><div className="area-benefits"><div><span>01</span><h2>ส่งข้อมูลทางไกล</h2><p>เริ่มประเมินจากข้อมูลดิจิทัลและส่งต้นฉบับเฉพาะรายการที่จำเป็น</p></div><div><span>02</span><h2>รู้ลำดับก่อนเริ่ม</h2><p>เห็นงานทะเบียน งานภาษี และกำหนดต่อเนื่องในแผนเดียว</p></div><div><span>03</span><h2>ติดตามกับทีมเดียว</h2><p>ลดการอธิบายข้อมูลซ้ำเมื่อใช้หลายบริการต่อเนื่อง</p></div></div><div className="section-heading split-heading"><div><p className="eyebrow"><span /> บริการที่มักเริ่มด้วยกัน</p><h2>พร้อมตั้งแต่วันแรก<br />และดูแลต่อได้</h2></div><p>เลือกดูข้อมูลเฉพาะแต่ละบริการ หรือส่งเป้าหมายมาให้ทีมช่วยจัดลำดับตามรูปแบบธุรกิจและที่ตั้งใน{province.name}</p></div><div className="related-grid area-services">{popular.map((s) => <Link href={`/services/${s.slug}`} key={s.slug}><span>{s.category}</span><h3>{s.title}</h3><p>{s.summary}</p><b>ดูรายละเอียด ↗</b></Link>)}</div>
      <section className="local-quality"><div><span>ข้อมูลพื้นที่ที่ควรตรวจ</span><h2>ก่อนเลือกที่ตั้งใน{province.name}</h2></div><ul><li>สิทธิใช้สถานที่และข้อจำกัดของอาคารหรือโครงการ</li><li>ความสอดคล้องระหว่างกิจกรรมจริงกับวัตถุประสงค์และใบอนุญาต</li><li>หลักฐานสถานประกอบการสำหรับภาษีมูลค่าเพิ่มหรือประกันสังคม</li><li>หน่วยงานท้องถิ่นที่กำกับป้าย อาคาร สุขลักษณะ หรือกิจการเฉพาะ</li></ul></section>
      <section className="area-faq"><div className="mini-heading"><span>คำถามในพื้นที่</span><h2>เริ่มธุรกิจใน{province.name}</h2></div><div className="faq-list">{areaFaqs.map((f, i) => <details open={i === 0} key={f.q}><summary><span>{f.q}</span><i aria-hidden="true">+</i></summary><p>{f.a}</p></details>)}</div></section><ConsultationCta title={`วางแผนเริ่มธุรกิจใน${province.name}`} /></div></section>
  </main><HubFooter /></>; }
