import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { LocalizedFooter, LocalizedHeader } from "@/components/LocalizedShell";
import { JsonLd } from "@/components/SeoBlocks";
import { categoryKey, dict, isLocale, languageAlternates, localizedPath, localizedPrice, localizedServiceTitle, localizedTime, locales, type Locale } from "@/lib/i18n";
import { categoryInfo, getService, services, siteUrl } from "@/lib/site-data";
import { serviceIcon, serviceImage } from "@/lib/service-visuals";

type Props = { params: Promise<{ locale: string; slug: string }> };
export function generateStaticParams() { return locales.flatMap((locale) => services.map((service) => ({ locale, slug: service.slug }))); }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale, slug } = await params; if (!isLocale(locale)) return {}; const service = getService(slug); if (!service) return {}; const t = dict(locale); const title = localizedServiceTitle(locale, slug); const path = `/services/${slug}`;
  return { title: { absolute: `${title} | ${t.brand}` }, description: t.service.summary.replace("{title}", title), alternates: { canonical: `${siteUrl}${localizedPath(locale, path)}`, languages: languageAlternates(path) }, openGraph: { title: `${title} | ${t.brand}`, description: t.service.summary.replace("{title}", title), url: `${siteUrl}${localizedPath(locale, path)}`, locale: t.htmlLang, images: ["/og.png"] } };
}

export default async function LocalizedServicePage({ params }: Props) {
  const { locale: raw, slug } = await params; if (!isLocale(raw)) notFound(); const locale: Locale = raw; const service = getService(slug); if (!service) notFound(); const t = dict(locale); const p = (path = "") => localizedPath(locale, path); const title = localizedServiceTitle(locale, slug); const category = categoryInfo[service.category];
  const related = services.filter((item) => item.category === service.category && item.slug !== service.slug).slice(0, 3);
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", name: title, description: t.service.summary.replace("{title}", title), inLanguage: t.htmlLang, provider: { "@type": "ProfessionalService", name: t.brand, url: `${siteUrl}/${locale}` }, areaServed: { "@type": "Country", name: "Thailand" } }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: t.nav.home, item: `${siteUrl}/${locale}` }, { "@type": "ListItem", position: 2, name: t.nav.services, item: `${siteUrl}/${locale}/services` }, { "@type": "ListItem", position: 3, name: title, item: `${siteUrl}/${locale}/services/${slug}` }] }, { "@type": "FAQPage", mainEntity: t.service.faqItems.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }] };
  return <><LocalizedHeader locale={locale} path={`/services/${slug}`} /><main className="inner-main" lang={t.htmlLang}><JsonLd data={schema} />
    <section className={`service-hero service-hero-v3 ${category.accent}`}><div className="container"><nav className="breadcrumbs" aria-label="Breadcrumb"><span><Link href={p()}>{t.nav.home}</Link><i>/</i></span><span><Link href={p("/services")}>{t.nav.services}</Link><i>/</i></span><span>{title}</span></nav><div className="service-hero-grid"><div className="service-hero-copy"><div className="service-title-row"><span className="service-hero-icon" aria-hidden="true">{serviceIcon(service.slug, service.category)}</span><p className="eyebrow"><span /> {t.category[categoryKey(service.category)].title}</p></div><h1>{title}<br /><em>{t.service.overview}</em></h1><p>{t.service.summary.replace("{title}", title)}</p><div className="hero-actions"><Link className="button button-primary" href={`${p()}#contact`}>{t.consult} <span aria-hidden="true">↗</span></Link><a className="button button-ghost" href="#details">{t.directory.details}</a></div></div><aside className="service-hero-panel"><figure><img src={serviceImage(service.category)} alt="" width="1280" height="720" loading="eager" decoding="async" fetchPriority="high" /><span aria-hidden="true">{serviceIcon(service.slug, service.category)}</span><figcaption><small>{t.category[categoryKey(service.category)].title}</small><strong>{title}</strong></figcaption></figure><div className="service-fact-card"><div className="fact-card-title"><span>{t.service.overview}</span><b>{t.directory.details}</b></div><dl><div><dt>{t.directory.price}</dt><dd>{localizedPrice(locale, service.price)}</dd></div><div><dt>{t.directory.time}</dt><dd>{localizedTime(locale, service.time)}</dd></div><div><dt>{t.language}</dt><dd>{t.htmlLang}</dd></div></dl><small>{t.tools.note}</small></div></aside></div></div></section>
    <section className="service-detail" id="details"><div className="container service-content-grid"><article className="longform"><section><span className="section-kicker">01</span><h2>{t.service.suitable}</h2><p>{t.service.suitableText}</p><p>{t.service.summary.replace("{title}", title)}</p></section><section><span className="section-kicker">02</span><h2>{t.service.documents}</h2><div className="document-list">{t.service.documentItems.map((item, index) => <div key={item}><i>{String(index + 1).padStart(2, "0")}</i><span>{item}</span></div>)}</div></section><section><span className="section-kicker">03</span><h2>{t.service.steps}</h2><ol className="step-list">{t.service.stepItems.map((item, index) => <li key={item}><span>{index + 1}</span><div><strong>{item}</strong></div></li>)}</ol></section><section><span className="section-kicker">04</span><h2>{t.service.faqTitle}</h2><div className="faq-list compact">{t.service.faqItems.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{question}</span><i aria-hidden="true">+</i></summary><p>{answer}</p></details>)}</div></section></article>
      <aside className="service-side"><div className="side-card"><span>{t.service.suitable}</span><p>{t.service.suitableText}</p><Link href={`${p()}#contact`}>{t.consult} <b aria-hidden="true">↗</b></Link></div><div className="side-card plain"><strong>{t.service.related}</strong>{related.map((item) => <Link href={p(`/services/${item.slug}`)} key={item.slug}>{localizedServiceTitle(locale, item.slug)}<span aria-hidden="true">→</span></Link>)}</div></aside>
    </div></section>
    <section className="related-section"><div className="container"><div className="mini-heading"><span>{t.service.related}</span><h2>{t.category[categoryKey(service.category)].title}</h2></div><div className="related-grid">{related.map((item) => <Link href={p(`/services/${item.slug}`)} key={item.slug}><span>{t.category[categoryKey(item.category)].title}</span><h3>{localizedServiceTitle(locale, item.slug)}</h3><p>{t.service.summary.replace("{title}", localizedServiceTitle(locale, item.slug))}</p><b>{t.directory.details} ↗</b></Link>)}</div></div></section>
  </main><LocalizedFooter locale={locale} /></>;
}
