import Link from "next/link";
import { Breadcrumbs, JsonLd } from "@/components/SeoBlocks";
import { industryCopy, industries, industryUi, industryDirectoryLead, type Industry } from "@/lib/industry-data";
import { getIndustryPermits, type PermitLevel } from "@/lib/industry-permits";
import { dict, localizedPath, localizedPrice, localizedServiceTitle, localizedTime, type LanguageCode, type Locale } from "@/lib/i18n";
import { serviceIcon } from "@/lib/service-visuals";
import { services, siteUrl } from "@/lib/site-data";

const isThai = (locale: LanguageCode) => locale === "th";
const coreCounts: Record<string, number> = { restaurant: 4, cafe: 4, "beauty-clinic": 5, "online-store": 4, factory: 6, hotel: 5, salon: 4, fitness: 4, "bubble-tea": 4, bakery: 5, school: 5, "it-company": 5, pharmacy: 6, "pet-business": 5 };
const permitLevel: Record<PermitLevel, { label: string; note: string }> = {
  required: { label: "จำเป็น", note: "เมื่อประกอบกิจกรรมตามหัวข้อนี้" },
  conditional: { label: "ตามเงื่อนไข", note: "ตรวจจากสินค้า บริการ หรือรูปแบบกิจการ" },
  scope: { label: "ต้องจำแนกก่อน", note: "ยืนยันกับหน่วยงานพื้นที่หรือหน่วยงานกำกับ" },
};
const guideLabels: Record<LanguageCode, { main: string; conditional: string; budget: string; budgetNote: string; recurring: string; includes: string; includedItems: string[]; overview: string }> = {
  th: { main: "งานเริ่มต้น", conditional: "งานตามเงื่อนไข", budget: "งบบริการเริ่มต้นโดยประมาณ", budgetNote: "รวมงานในแผนนี้ ยังไม่รวมค่าราชการ VAT และค่าใช้จ่ายเฉพาะกรณี", recurring: "+ ค่าดูแลรายเดือนถ้าเลือก", includes: "ในบริการนี้", includedItems: ["ประเมินความจำเป็น", "ตรวจข้อมูลและเอกสาร", "ติดตามและส่งมอบหลักฐาน"], overview: "สรุปแผนเปิดธุรกิจ" },
  en: { main: "Start-up work", conditional: "Case-dependent work", budget: "Estimated starting service budget", budgetNote: "For the workstreams shown; excludes government fees, VAT and case-specific costs.", recurring: "+ recurring services if selected", includes: "What this service covers", includedItems: ["Assess whether it applies", "Review facts and documents", "Track and hand over evidence"], overview: "Launch-plan summary" },
  my: { main: "စတင်ရန်အလုပ်", conditional: "အခြေအနေအလိုက်", budget: "ခန့်မှန်းစတင်ဝန်ဆောင်ခ", budgetNote: "အစိုးရကြေး၊ VAT နှင့် အမှုလိုက်ကုန်ကျစရိတ်မပါ။", recurring: "+ ရွေးချယ်ပါက လစဉ်ကုန်ကျစရိတ်", includes: "ဝန်ဆောင်မှုပါဝင်မှု", includedItems: ["လိုအပ်ချက်စစ်ဆေး", "အချက်အလက်နှင့် စာရွက်စာတမ်းစစ်ဆေး", "အခြေအနေလိုက်ပြီး အထောက်အထားပေးအပ်"], overview: "စတင်မှုအစီအစဉ်" },
  hi: { main: "शुरुआती कार्य", conditional: "स्थिति-आधारित कार्य", budget: "अनुमानित शुरुआती सेवा बजट", budgetNote: "सरकारी शुल्क, VAT और विशेष मामले की लागत शामिल नहीं।", recurring: "+ चुनी गई मासिक सेवाएँ", includes: "सेवा में क्या शामिल है", includedItems: ["आवश्यकता का आकलन", "तथ्य और दस्तावेज़ जाँच", "प्रगति और साक्ष्य सौंपना"], overview: "लॉन्च योजना" },
  zh: { main: "启动必查事项", conditional: "视情况而定", budget: "预计起步服务预算", budgetNote: "包含本页所列服务，不含政府费、增值税及个案费用。", recurring: "+ 如选择持续服务，另计月费", includes: "服务内容", includedItems: ["评估是否适用", "审核信息与文件", "跟进并交付证明"], overview: "开业计划摘要" },
};

function startingBudget(items: typeof services) {
  return items.filter((item) => !item.price.includes("เดือน")).reduce((total, item) => total + Number((item.price.match(/[\d,]+/)?.[0] ?? "0").replace(/,/g, "")), 0);
}

export function IndustryDirectory({ locale = "th" }: { locale?: LanguageCode }) {
  const ui = industryUi[locale]; const p = (route: string) => localizedPath(locale, route); const directoryLead = industryDirectoryLead(locale);
  const schema = { "@context": "https://schema.org", "@type": "ItemList", name: ui.directoryTitle, itemListElement: industries.map((industry, index) => ({ "@type": "ListItem", position: index + 1, name: industryCopy(industry, locale).title, url: `${siteUrl}${p(`/business-guides/${industry.slug}`)}` })) };
  return <><JsonLd data={schema} />
    <section className="industry-directory-hero"><div className="container"><Breadcrumbs items={[{ label: isThai(locale) ? "หน้าหลัก" : dict(locale as Locale).nav.home, href: p("") }, { label: ui.nav }]} /><div className="industry-directory-hero-grid"><div data-reveal><p className="eyebrow"><span /> {ui.eyebrow}</p><h1>{ui.title.split("\n").map((line, index) => <span key={line}>{line}{index === 0 && <br />}</span>)}</h1><p>{ui.lead}</p><div className="industry-hero-proof"><span><strong>{industries.length}</strong>{ui.directoryTitle}</span><span><strong>40</strong>{isThai(locale) ? "บริการที่เชื่อมถึงกัน" : dict(locale as Locale).directory.count}</span><span><strong>5</strong>{isThai(locale) ? "ภาษา" : dict(locale as Locale).language}</span></div></div><figure data-reveal><img src="/illustration-industries-v7.webp" alt="" width="1280" height="720" loading="eager" decoding="async" /><figcaption>{directoryLead}</figcaption></figure></div></div></section>
    <section className="section industry-directory"><div className="container"><div className="section-heading split-heading" data-reveal><div><p className="eyebrow"><span /> {industries.length} BUSINESS PLAYBOOKS</p><h2>{ui.directoryTitle}</h2></div><p>{directoryLead}</p></div><div className="industry-grid">{industries.map((industry, index) => { const copy = industryCopy(industry, locale); return <Link className={`industry-card ${industry.tone}`} href={p(`/business-guides/${industry.slug}`)} key={industry.slug} data-reveal style={{ "--reveal-delay": `${Math.min(index % 4, 3) * 70}ms` } as React.CSSProperties}><span className="industry-icon" aria-hidden="true">{industry.icon}</span><small>{String(index + 1).padStart(2, "0")} / {industry.serviceSlugs.length} {ui.taskCount}</small><h2>{copy.shortTitle}</h2><h3>{copy.title}</h3><p>{copy.summary}</p><b>{ui.explore} <span aria-hidden="true">↗</span></b></Link>; })}</div></div></section>
  </>;
}

export function IndustryGuide({ industry, locale = "th" }: { industry: Industry; locale?: LanguageCode }) {
  const ui = industryUi[locale]; const copy = industryCopy(industry, locale); const p = (route: string) => localizedPath(locale, route);
  const t = isThai(locale) ? null : dict(locale as Locale);
  const relatedIndustries = industries.filter((item) => item.slug !== industry.slug).slice(0, 3);
  const relatedServices = industry.serviceSlugs.map((slug) => services.find((service) => service.slug === slug)).filter((service): service is NonNullable<typeof service> => Boolean(service));
  const serviceTitle = (slug: string) => isThai(locale) ? services.find((item) => item.slug === slug)?.title ?? slug : localizedServiceTitle(locale as Locale, slug);
  const serviceSummary = (slug: string, summary: string) => isThai(locale) ? summary : t!.service.summary.replace("{title}", serviceTitle(slug));
  const faqs = ui.faqs;
  const labels = guideLabels[locale]; const coreCount = coreCounts[industry.slug] ?? Math.ceil(relatedServices.length / 2); const budget = startingBudget(relatedServices);
  const permits = getIndustryPermits(industry.slug);
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "HowTo", name: copy.title, description: copy.summary, inLanguage: isThai(locale) ? "th" : t!.htmlLang, step: ui.steps.map((name, index) => ({ "@type": "HowToStep", position: index + 1, name })) },
    { "@type": "FAQPage", mainEntity: faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: isThai(locale) ? "หน้าหลัก" : t!.nav.home, item: `${siteUrl}${p("")}` }, { "@type": "ListItem", position: 2, name: ui.nav, item: `${siteUrl}${p("/business-guides")}` }, { "@type": "ListItem", position: 3, name: copy.title, item: `${siteUrl}${p(`/business-guides/${industry.slug}`)}` }] },
  ] };
  return <><JsonLd data={schema} />
    <section className={`industry-guide-hero ${industry.tone}`}><div className="container"><Breadcrumbs items={[{ label: isThai(locale) ? "หน้าหลัก" : t!.nav.home, href: p("") }, { label: ui.nav, href: p("/business-guides") }, { label: copy.shortTitle }]} /><div className="industry-guide-hero-grid" data-reveal><div><span className="industry-guide-icon" aria-hidden="true">{industry.icon}</span><p className="eyebrow"><span /> {ui.eyebrow}</p><h1>{copy.title}</h1><p>{copy.summary}</p><div className="hero-actions"><Link className="button button-primary" href={`${p("")}#contact`}>{ui.cta} <span aria-hidden="true">↗</span></Link><a className="button button-ghost" href="#checklist">{ui.checklistTitle}</a></div></div><aside className="industry-visual-panel"><figure><img src="/illustration-industries-v7.webp" alt="" width="1280" height="720" loading="eager" decoding="async" /><span aria-hidden="true">{industry.icon}</span></figure><div><small>{labels.overview}</small><strong>{relatedServices.length} {ui.taskCount}</strong><p>{coreCount} {labels.main} · {relatedServices.length - coreCount} {labels.conditional}</p></div></aside></div></div></section>
    <section className="section industry-guide-content"><div className="container"><div className="risk-callout" data-reveal><span aria-hidden="true">!</span><div><strong>{ui.riskTitle}</strong><p>{copy.risk}</p></div></div>
      <div className="industry-cost-summary" data-reveal><div><small>{labels.budget}</small><strong>{isThai(locale) ? `ประมาณ ${budget.toLocaleString("th-TH")} บาทขึ้นไป` : `From THB ${budget.toLocaleString("en-US")}`}</strong><p>{labels.budgetNote}</p></div><dl><div><dt>{labels.main}</dt><dd>{coreCount}</dd></div><div><dt>{labels.conditional}</dt><dd>{relatedServices.length - coreCount}</dd></div><div><dt>{labels.recurring}</dt><dd>{relatedServices.some((item) => item.price.includes("เดือน")) ? "✓" : "—"}</dd></div></dl></div>
      <div className="industry-section-heading" id="checklist" data-reveal><span>01</span><div><p className="eyebrow"><span /> CHECKLIST</p><h2>{ui.checklistTitle}</h2><p>{ui.checklistLead}</p></div></div>
      <div className="industry-service-grid detailed">{relatedServices.map((service, index) => <article className={index < coreCount ? "core" : "conditional"} key={service.slug} data-reveal style={{ "--reveal-delay": `${Math.min(index % 3, 2) * 70}ms` } as React.CSSProperties}><div className="industry-service-top"><span className="service-card-icon" aria-hidden="true">{serviceIcon(service.slug, service.category)}</span><div><small>{String(index + 1).padStart(2, "0")} / {relatedServices.length}</small><b>{index < coreCount ? labels.main : labels.conditional}</b></div></div><h3>{serviceTitle(service.slug)}</h3><p>{serviceSummary(service.slug, service.summary)}</p><div className="industry-includes"><strong>{labels.includes}</strong>{labels.includedItems.map((item) => <span key={item}>✓ {item}</span>)}</div><dl><div><dt>{ui.startingPrice}</dt><dd>{isThai(locale) ? service.price : localizedPrice(locale as Locale, service.price)}</dd></div><div><dt>{ui.timeline}</dt><dd>{isThai(locale) ? service.time : localizedTime(locale as Locale, service.time)}</dd></div></dl><Link href={p(`/services/${service.slug}`)}>{isThai(locale) ? "ดูรายละเอียด เอกสาร และ FAQ" : t!.directory.details} <span aria-hidden="true">↗</span></Link></article>)}</div>
      <div className="industry-two-column"><section data-reveal><div className="industry-section-heading compact"><span>02</span><h2>{ui.stepsTitle}</h2></div><ol>{ui.steps.map((step, index) => <li key={step}><span>{index + 1}</span><p>{step}</p></li>)}</ol></section><section data-reveal><div className="industry-section-heading compact"><span>03</span><h2>{ui.documentsTitle}</h2></div><ul>{ui.documents.map((document) => <li key={document}><span aria-hidden="true">✓</span>{document}</li>)}</ul></section></div>
      <section className="industry-faq" data-reveal><div className="industry-section-heading"><span>04</span><h2>{ui.faqTitle}</h2></div><div className="faq-list">{faqs.map(([q, a], index) => <details key={q} open={index === 0}><summary><span>{q}</span><i>+</i></summary><p>{a}</p></details>)}</div></section>
      <section className="related-industry" data-reveal><div className="mini-heading"><span>{ui.relatedTitle}</span><h2>{ui.relatedTitle}</h2></div><div>{relatedIndustries.map((item) => { const itemCopy = industryCopy(item, locale); return <Link href={p(`/business-guides/${item.slug}`)} key={item.slug}><span aria-hidden="true">{item.icon}</span><small>{itemCopy.shortTitle}</small><strong>{itemCopy.title}</strong><b>↗</b></Link>; })}</div></section>
      {isThai(locale) && permits.length > 0 && <section className="industry-permit-section" id="permits" data-reveal><div className="industry-permit-scope"><span aria-hidden="true">i</span><div><strong>ข้อมูลตรวจสอบเพิ่มเติม — ไม่รวมในแพ็กเกจบริการด้านบน</strong><p>รายการนี้ช่วยให้เห็นใบอนุญาตที่กิจการอาจต้องมี หากต้องการให้ทีมดำเนินการ ต้องประเมินขอบเขต ระยะเวลา และเสนอราคาแยกก่อนเริ่มงาน</p></div></div><div className="industry-permit-head"><div><p className="eyebrow"><span /> ตรวจจากแหล่งข้อมูลราชการ</p><h2>ใบอนุญาตเฉพาะทาง<br />ที่ควรตรวจเพิ่มเติม</h2></div><div className="industry-permit-summary"><strong>{permits.length}</strong><span>หัวข้อที่ควรตรวจ<br />ก่อนเซ็นสัญญาหรือลงทุน</span></div></div><p className="industry-permit-lead">คำว่า “จำเป็น” หมายถึงจำเป็นเมื่อธุรกิจทำกิจกรรมตามรายละเอียดของหัวข้อนั้น ส่วนรายการตามเงื่อนไขต้องจำแนกจากบริการ สินค้า สถานที่ และพื้นที่จริง</p><div className="industry-permit-grid">{permits.map((permit, index) => <article className={`permit-card ${permit.level}`} key={`${permit.title}-${index}`}><div className="permit-card-top"><span>{permitLevel[permit.level].label}</span><b>{String(index + 1).padStart(2, "0")}</b></div><h3>{permit.title}</h3>{permit.form && <p className="permit-form">แบบหรือเอกสาร: <strong>{permit.form}</strong></p>}<p>{permit.summary}</p><dl><div><dt>ผู้ถือหรือผู้ขอ</dt><dd>{permit.holder}</dd></div><div><dt>หน่วยงานหลัก</dt><dd>{permit.authority}</dd></div></dl><small>{permitLevel[permit.level].note}</small><a href={permit.source} target="_blank" rel="noreferrer">ตรวจข้อมูลจากหน่วยงานรัฐ <span aria-hidden="true">↗</span></a></article>)}</div><footer><span aria-hidden="true">✓</span><p><strong>ตรวจทานข้อมูลล่าสุด 10 สิงหาคม 2569</strong> กฎหมาย ข้อบัญญัติท้องถิ่น และแบบคำขออาจเปลี่ยนได้ ควรยืนยันกับหน่วยงานเจ้าของเรื่องก่อนยื่นหรือชำระค่าใช้จ่าย</p></footer></section>}
      <div className="industry-final-cta" data-reveal><span aria-hidden="true">{industry.icon}</span><div><small>{copy.shortTitle}</small><h2>{ui.ctaTitle}</h2></div><Link className="button button-primary" href={`${p("")}#contact`}>{ui.cta} <span aria-hidden="true">↗</span></Link></div>
    </div></section>
  </>;
}
