import type { LanguageCode, Locale } from "@/lib/i18n";

type IndustryTranslation = { title: string; shortTitle: string; summary: string; risk: string };
export type Industry = { slug: string; icon: string; tone: string; serviceSlugs: string[]; copy: Record<LanguageCode, IndustryTranslation> };

export const industries: Industry[] = [
  { slug: "restaurant", icon: "🍜", tone: "coral", serviceSlugs: ["register-company", "commercial-registration", "vat-registration", "social-security", "monthly-accounting", "fda-registration", "trademark"], copy: {
    th: { title: "เปิดร้านอาหารต้องทำอะไรบ้าง", shortTitle: "ร้านอาหาร", summary: "เช็กรูปแบบกิจการ ทะเบียน ภาษี ลูกจ้าง อาหารและป้ายร้านก่อนเปิดขาย", risk: "สถานที่และรูปแบบการปรุงอาหารมีผลต่อใบอนุญาตที่ต้องตรวจเพิ่ม" },
    en: { title: "How to open a restaurant in Thailand", shortTitle: "Restaurant", summary: "Check the business structure, registrations, tax, employees, food requirements and storefront matters before opening.", risk: "The premises and food-preparation model can change the licences and local approvals you need." },
    my: { title: "ထိုင်းနိုင်ငံတွင် စားသောက်ဆိုင်ဖွင့်ရန်", shortTitle: "စားသောက်ဆိုင်", summary: "လုပ်ငန်းပုံစံ၊ မှတ်ပုံတင်၊ အခွန်၊ ဝန်ထမ်း၊ အစားအသောက်ဆိုင်ရာနှင့် ဆိုင်အမှတ်အသားများကို ဖွင့်မီစစ်ဆေးပါ။", risk: "နေရာနှင့် အစားအသောက်ပြင်ဆင်မှုပုံစံသည် လိုင်စင်လိုအပ်ချက်ကို ပြောင်းလဲစေနိုင်သည်။" },
    hi: { title: "थाईलैंड में रेस्तरां कैसे खोलें", shortTitle: "रेस्तरां", summary: "खोलने से पहले व्यवसाय संरचना, पंजीकरण, कर, कर्मचारी, खाद्य नियम और दुकान संबंधी अनुमति जाँचें।", risk: "स्थान और खाना तैयार करने का तरीका आवश्यक लाइसेंस बदल सकता है।" },
    zh: { title: "如何在泰国开餐厅", shortTitle: "餐厅", summary: "开业前检查企业结构、登记、税务、员工、食品要求及门店事项。", risk: "场地和食品制作方式会影响所需许可证与地方审批。" },
  } },
  { slug: "cafe", icon: "☕", tone: "sand", serviceSlugs: ["commercial-registration", "register-company", "vat-registration", "social-security", "monthly-accounting", "trademark"], copy: {
    th: { title: "เปิดร้านกาแฟต้องขออะไรบ้าง", shortTitle: "ร้านกาแฟ", summary: "วางรูปแบบร้าน จดทะเบียน เช็ก VAT ลูกจ้าง บัญชี และคุ้มครองชื่อร้านให้พร้อมขยาย", risk: "อาหารที่ผลิตเองและการใช้พื้นที่อาจทำให้ต้องตรวจข้อกำหนดเพิ่ม" },
    en: { title: "How to open a café in Thailand", shortTitle: "Café", summary: "Plan the store structure, registration, VAT, employees, accounting and trademark protection before you scale.", risk: "On-site food production and how the premises are used may trigger additional local requirements." },
    my: { title: "ထိုင်းနိုင်ငံတွင် ကော်ဖီဆိုင်ဖွင့်ရန်", shortTitle: "ကော်ဖီဆိုင်", summary: "ဆိုင်ပုံစံ၊ မှတ်ပုံတင်၊ VAT၊ ဝန်ထမ်း၊ စာရင်းကိုင်နှင့် ကုန်အမှတ်တံဆိပ်ကို ကြိုတင်စီစဉ်ပါ။", risk: "ဆိုင်တွင် အစားအသောက်ထုတ်လုပ်မှုနှင့် နေရာအသုံးပြုပုံက ထပ်မံစစ်ဆေးမှုလိုအပ်နိုင်သည်။" },
    hi: { title: "थाईलैंड में कैफ़े कैसे खोलें", shortTitle: "कैफ़े", summary: "दुकान संरचना, पंजीकरण, VAT, कर्मचारी, लेखांकन और ट्रेडमार्क सुरक्षा की योजना बनाएँ।", risk: "स्थान पर खाद्य निर्माण और परिसर का उपयोग अतिरिक्त शर्तें ला सकता है।" },
    zh: { title: "如何在泰国开咖啡店", shortTitle: "咖啡店", summary: "在扩张前规划门店结构、登记、增值税、员工、会计和商标保护。", risk: "现场食品制作和场地用途可能引发额外的地方要求。" },
  } },
  { slug: "beauty-clinic", icon: "💄", tone: "rose", serviceSlugs: ["register-company", "vat-registration", "social-security", "monthly-accounting", "fda-registration", "trademark", "employment-contracts"], copy: {
    th: { title: "เปิดคลินิกความงามต้องมีใบอนุญาตอะไร", shortTitle: "คลินิกความงาม", summary: "แยกงานนิติบุคคล สถานพยาบาล ผู้ประกอบวิชาชีพ ผลิตภัณฑ์ ลูกจ้าง และภาษีให้ชัดเจน", risk: "ใบอนุญาตสถานพยาบาลและใบประกอบวิชาชีพต้องตรวจกับหน่วยงานเฉพาะโดยตรง" },
    en: { title: "How to open a beauty clinic in Thailand", shortTitle: "Beauty clinic", summary: "Separate company, medical-facility, professional, product, employee and tax requirements into one launch plan.", risk: "Medical-facility and professional licences must be confirmed directly with the relevant health authorities." },
    my: { title: "ထိုင်းနိုင်ငံတွင် အလှအပဆေးခန်းဖွင့်ရန်", shortTitle: "အလှအပဆေးခန်း", summary: "ကုမ္ပဏီ၊ ဆေးရုံလိုင်စင်၊ ပညာရှင်၊ ထုတ်ကုန်၊ ဝန်ထမ်းနှင့် အခွန်လိုအပ်ချက်များကို စီစဉ်ပါ။", risk: "ဆေးရုံနှင့် ပညာရှင်လိုင်စင်များကို ကျန်းမာရေးအာဏာပိုင်များနှင့် တိုက်ရိုက်အတည်ပြုရန် လိုသည်။" },
    hi: { title: "थाईलैंड में ब्यूटी क्लिनिक कैसे खोलें", shortTitle: "ब्यूटी क्लिनिक", summary: "कंपनी, चिकित्सा केंद्र, पेशेवर, उत्पाद, कर्मचारी और कर आवश्यकताओं को एक योजना में रखें।", risk: "चिकित्सा केंद्र और पेशेवर लाइसेंस संबंधित स्वास्थ्य प्राधिकरण से पुष्ट करें।" },
    zh: { title: "如何在泰国开美容诊所", shortTitle: "美容诊所", summary: "将公司、医疗机构、专业人员、产品、员工及税务要求整合为一份开业计划。", risk: "医疗机构及专业执照需直接向相关卫生机构确认。" },
  } },
  { slug: "online-store", icon: "🛒", tone: "blue", serviceSlugs: ["commercial-registration", "register-company", "vat-registration", "trademark", "monthly-accounting", "e-tax-invoice", "pdpa-starter"], copy: {
    th: { title: "เปิดร้านค้าออนไลน์ต้องจดอะไร", shortTitle: "ร้านค้าออนไลน์", summary: "เลือกทะเบียน วางระบบภาษี เอกสารขาย เครื่องหมายการค้า และ PDPA ตามช่องทางขาย", risk: "สินค้าบางประเภทต้องขออนุญาตเพิ่มก่อนโฆษณาหรือจัดส่ง" },
    en: { title: "How to open an online store in Thailand", shortTitle: "Online store", summary: "Choose the right registration and prepare tax, sales documents, trademark and PDPA work for your selling channels.", risk: "Some product categories require an additional approval before they can be advertised or shipped." },
    my: { title: "ထိုင်းနိုင်ငံတွင် အွန်လိုင်းဆိုင်ဖွင့်ရန်", shortTitle: "အွန်လိုင်းဆိုင်", summary: "သင့်လျော်သော မှတ်ပုံတင်ပုံစံကိုရွေးချယ်ပြီး အခွန်၊ ရောင်းချရေးစာရွက်စာတမ်း၊ ကုန်အမှတ်တံဆိပ်နှင့် PDPA ကိုပြင်ဆင်ပါ။", risk: "ကုန်ပစ္စည်းအချို့သည် ကြော်ငြာခြင်းသို့မဟုတ် ပို့ဆောင်ခြင်းမပြုမီ ထပ်မံအတည်ပြုချက်လိုအပ်သည်။" },
    hi: { title: "थाईलैंड में ऑनलाइन स्टोर कैसे खोलें", shortTitle: "ऑनलाइन स्टोर", summary: "सही पंजीकरण चुनें और कर, बिक्री दस्तावेज़, ट्रेडमार्क और PDPA तैयार करें।", risk: "कुछ उत्पादों के विज्ञापन या शिपमेंट से पहले अतिरिक्त अनुमति चाहिए।" },
    zh: { title: "如何在泰国开网店", shortTitle: "网店", summary: "选择合适的登记方式，并为销售渠道准备税务、销售文件、商标及 PDPA。", risk: "某些产品类别在广告或发货前需要额外批准。" },
  } },
  { slug: "factory", icon: "🏭", tone: "olive", serviceSlugs: ["register-company", "factory-license", "vat-registration", "social-security", "gmp", "iso", "import-export"], copy: {
    th: { title: "เปิดโรงงานต้องขออนุญาตอะไร", shortTitle: "โรงงาน", summary: "ตรวจที่ดิน อาคาร กำลังเครื่องจักร ประเภทการผลิต แรงงาน ภาษี และมาตรฐานก่อลงทุน", risk: "อย่าเริ่มซื้อเครื่องจักรหรือเซ็นสัญญาพื้นที่ก่อนตรวจข้อจำกัดการใช้ประโยชน์" },
    en: { title: "How to open a factory in Thailand", shortTitle: "Factory", summary: "Check land use, buildings, machinery, production type, labour, tax and standards before committing capital.", risk: "Do not buy machinery or sign a long lease before checking land-use and factory restrictions." },
    my: { title: "ထိုင်းနိုင်ငံတွင် စက်ရုံဖွင့်ရန်", shortTitle: "စက်ရုံ", summary: "မတည်ငွေမလုပ်မီ မြေအသုံးပြုမှု၊ အဆောက်အအုံ၊ စက်ပစ္စည်း၊ ထုတ်လုပ်မှုအမျိုးအစား၊ အလုပ်သမား၊ အခွန်နှင့် စံနှုန်းများကိုစစ်ဆေးပါ။", risk: "မြေအသုံးပြုမှုနှင့် စက်ရုံကန့်သတ်ချက်ကိုမစစ်မီ စက်ပစ္စည်းမဝယ်ပါနှင့်။" },
    hi: { title: "थाईलैंड में फ़ैक्ट्री कैसे खोलें", shortTitle: "फ़ैक्ट्री", summary: "निवेश से पहले भूमि उपयोग, भवन, मशीनरी, उत्पादन, श्रम, कर और मानकों की जाँच करें।", risk: "भूमि उपयोग और फ़ैक्ट्री पाबंदियाँ जाँचने से पहले मशीनरी न खरीदें।" },
    zh: { title: "如何在泰国开工厂", shortTitle: "工厂", summary: "投入资金前，检查土地用途、建筑、机械、生产类型、用工、税务与标准。", risk: "确认土地用途和工厂限制前，不要先购买机械或签长租约。" },
  } },
  { slug: "hotel", icon: "🏨", tone: "violet", serviceSlugs: ["register-company", "vat-registration", "social-security", "monthly-accounting", "trademark", "business-contract-review", "pdpa-starter"], copy: {
    th: { title: "เปิดโรงแรมต้องใช้เอกสารอะไร", shortTitle: "โรงแรม", summary: "เช็กอาคาร การใช้ประโยชน์ ใบอนุญาตโรงแรม บริษัท ภาษี พนักงาน สัญญา และข้อมูลผู้เข้าพัก", risk: "ควรตรวจอาคารและผังเมืองก่อลงทุนปรับปรุงสถานที่" },
    en: { title: "How to open a hotel in Thailand", shortTitle: "Hotel", summary: "Check building use, hotel licensing, company, tax, employees, contracts and guest-data requirements.", risk: "Confirm building and town-planning eligibility before investing in renovations." },
    my: { title: "ထိုင်းနိုင်ငံတွင် ဟိုတယ်ဖွင့်ရန်", shortTitle: "ဟိုတယ်", summary: "အဆောက်အအုံအသုံးပြုမှု၊ ဟိုတယ်လိုင်စင်၊ ကုမ္ပဏီ၊ အခွန်၊ ဝန်ထမ်း၊ စာချုပ်နှင့် ဧည့်သည်အချက်အလက်ကိုစစ်ဆေးပါ။", risk: "ပြင်ဆင်မှုတွင် မရင်းနှီးမှီ အဆောက်အအုံနှင့် မြို့ပြစီမံကိန်းကိုအတည်ပြုပါ။" },
    hi: { title: "थाईलैंड में होटल कैसे खोलें", shortTitle: "होटल", summary: "भवन उपयोग, होटल लाइसेंस, कंपनी, कर, कर्मचारी, अनुबंध और अतिथि डेटा की जाँच करें।", risk: "नवीनीकरण से पहले भवन और नगर नियोजन पात्रता पुष्ट करें।" },
    zh: { title: "如何在泰国开酒店", shortTitle: "酒店", summary: "检查建筑用途、酒店许可、公司、税务、员工、合同及客人数据要求。", risk: "投资装修前，请先确认建筑和城市规划条件。" },
  } },
  { slug: "salon", icon: "💇", tone: "mint", serviceSlugs: ["commercial-registration", "register-company", "vat-registration", "social-security", "monthly-accounting", "trademark"], copy: {
    th: { title: "เปิดร้านเสริมสวยต้องทำอะไร", shortTitle: "ร้านเสริมสวย", summary: "เลือกรูปแบบกิจการ จดทะเบียน เช็กภาษี จ้างงาน บัญชี ผลิตภัณฑ์ที่ใช้ และชื่อร้าน", risk: "บริการบางประเภทอาจเข้าข่ายสถานพยาบาล ควรแยกขอบเขตบริการให้ชัด" },
    en: { title: "How to open a beauty salon in Thailand", shortTitle: "Beauty salon", summary: "Choose a structure and prepare registration, tax, employment, accounting, product and brand-name work.", risk: "Some treatment types may fall under medical-facility rules; define the service scope carefully." },
    my: { title: "ထိုင်းနိုင်ငံတွင် အလှပြင်ဆိုင်ဖွင့်ရန်", shortTitle: "အလှပြင်ဆိုင်", summary: "လုပ်ငန်းပုံစံ၊ မှတ်ပုံတင်၊ အခွန်၊ ဝန်ထမ်း၊ စာရင်းကိုင်၊ ထုတ်ကုန်နှင့် ဆိုင်အမည်ကို ပြင်ဆင်ပါ။", risk: "ကုသမှုအချို့သည် ဆေးရုံစည်းမျဉ်းများနှင့်ဆိုင်နိုင်သည်။" },
    hi: { title: "थाईलैंड में ब्यूटी सलून कैसे खोलें", shortTitle: "ब्यूटी सलून", summary: "संरचना चुनें और पंजीकरण, कर, रोज़गार, लेखांकन, उत्पाद और ब्रांड की तैयारी करें।", risk: "कुछ उपचार चिकित्सा केंद्र नियमों में आ सकते हैं।" },
    zh: { title: "如何在泰国开美容院", shortTitle: "美容院", summary: "选择企业结构，准备登记、税务、用工、会计、产品和品牌事项。", risk: "某些护理项目可能适用医疗机构规则，需明确服务范围。" },
  } },
  { slug: "fitness", icon: "🏋️", tone: "blue", serviceSlugs: ["register-company", "commercial-registration", "vat-registration", "social-security", "business-contract-review", "pdpa-starter", "monthly-accounting"], copy: {
    th: { title: "เปิดฟิตเนสต้องขออนุญาตอะไร", shortTitle: "ฟิตเนส", summary: "ตรวจนิติบุคคล อาคาร สัญญาสมาชิก ความรับผิด พนักงาน ภาษี และข้อมูลสุขภาพสมาชิก", risk: "อาคาร ความปลอดภัย และข้อกำหนดอุปกรณ์ควรตรวจก่อเปิดรับสมาชิก",},
    en: { title: "How to open a fitness studio in Thailand", shortTitle: "Fitness studio", summary: "Check the legal entity, building, membership contract, liability, employees, tax and member health data.", risk: "Building safety and equipment requirements should be checked before accepting memberships." },
    my: { title: "ထိုင်းနိုင်ငံတွင် အားကစားရုံဖွင့်ရန်", shortTitle: "အားကစားရုံ", summary: "လုပ်ငန်းပုံစံ၊ အဆောက်အအုံ၊ အဖွဲ့ဝင်စာချုပ်၊ တာဝန်ယူမှု၊ ဝန်ထမ်း၊ အခွန်နှင့် ကျန်းမာရေးဒေတာကိုစစ်ဆေးပါ။", risk: "အဖွဲ့ဝင်များကိုလက်မခံမီ အဆောက်အအုံနှင့် စက်ပစ္စည်းလုံခြုံမှုကိုစစ်ဆေးပါ။" },
    hi: { title: "थाईलैंड में फ़िटनेस स्टूडियो कैसे खोलें", shortTitle: "फ़िटनेस", summary: "कानूनी इकाई, भवन, सदस्यता अनुबंध, देयता, कर्मचारी, कर और स्वास्थ्य डेटा जाँचें।", risk: "सदस्यता लेने से पहले भवन और उपकरण सुरक्षा की जाँच करें।" },
    zh: { title: "如何在泰国开健身房", shortTitle: "健身房", summary: "检查法律实体、建筑、会员合同、责任、员工、税务及会员健康数据。", risk: "接受会员前，应检查建筑安全与设备要求。" },
  } },
  { slug: "bubble-tea", icon: "🧋", tone: "coral", serviceSlugs: ["commercial-registration", "register-company", "vat-registration", "social-security", "monthly-accounting", "fda-registration", "trademark"], copy: {
    th: { title: "เปิดร้านชาไข่มุกต้องจดอะไร", shortTitle: "ร้านชาไข่มุก", summary: "เช็กทะเบียน ภาษี ลูกจ้าง บัญชี สถานที่ วัตถุดิบ ผลิตภัณฑ์บรรจุ และชื่อร้าน", risk: "ถ้าผลิตวัตถุดิบหรือเครื่องดื่มบรรจุเอง อาจมีงาน อย. เพิ่ม" },
    en: { title: "How to open a bubble tea shop in Thailand", shortTitle: "Bubble tea shop", summary: "Check registration, tax, employees, accounting, premises, ingredients, packaged products and brand protection.", risk: "Making packaged ingredients or bottled drinks may add Thai FDA work." },
    my: { title: "ထိုင်းနိုင်ငံတွင် ဘတ်ဘလ်တီဆိုင်ဖွင့်ရန်", shortTitle: "ဘတ်ဘလ်တီဆိုင်", summary: "မှတ်ပုံတင်၊ အခွန်၊ ဝန်ထမ်း၊ စာရင်းကိုင်၊ နေရာ၊ ပစ္စည်း၊ ထုပ်ပိုးထုတ်ကုန်နှင့် ကုန်အမှတ်တံဆိပ်ကိုစစ်ဆေးပါ။", risk: "ထုပ်ပိုးပစ္စည်းသို့မဟုတ် ပုလင်းဖြင့်ရောင်းသောအဖျော်ယမကာများကိုထုတ်လုပ်ပါက FDA အလုပ်လိုအပ်နိုင်သည်။" },
    hi: { title: "थाईलैंड में बबल टी शॉप कैसे खोलें", shortTitle: "बबल टी", summary: "पंजीकरण, कर, कर्मचारी, लेखांकन, परिसर, सामग्री, पैकेज्ड उत्पाद और ब्रांड जाँचें।", risk: "पैकेज्ड सामग्री या बोतलबंद पेय बनाने पर Thai FDA का काम बढ़ सकता है।" },
    zh: { title: "如何在泰国开珍珠奶茶店", shortTitle: "珍珠奶茶店", summary: "检查登记、税务、员工、会计、场地、原料、预包装产品及品牌保护。", risk: "自制预包装原料或瓶装饮料可能增加泰国 FDA 手续。" },
  } },
  { slug: "bakery", icon: "🥐", tone: "sand", serviceSlugs: ["commercial-registration", "register-company", "vat-registration", "social-security", "monthly-accounting", "fda-registration", "gmp", "trademark"], copy: {
    th: { title: "เปิดร้านเบเกอรี่ต้องทำอะไร", shortTitle: "ร้านเบเกอรี่", summary: "แยกการขายหน้าร้านกับการผลิตบรรจุ แล้วเช็กทะเบียน ภาษี ลูกจ้าง อย. GMP และชื่อร้าน", risk: "การผลิตส่งร้านค้าหรือขายปลีกแบบบรรจุมีขอบเขตกำกับต่างจากอบขายสด",},
    en: { title: "How to open a bakery in Thailand", shortTitle: "Bakery", summary: "Separate fresh retail sales from packaged production, then check registration, tax, employees, Thai FDA, GMP and brand work.", risk: "Wholesale or packaged retail production has a different compliance scope from fresh counter sales." },
    my: { title: "ထိုင်းနိုင်ငံတွင် မုန့်ဖုတ်ဆိုင်ဖွင့်ရန်", shortTitle: "မုန့်ဖုတ်ဆိုင်", summary: "လတ်ဆတ်လက်လီရောင်းချမှုနှင့် ထုပ်ပိုးထုတ်လုပ်မှုကိုခွဲပြီး မှတ်ပုံတင်၊ အခွန်၊ ဝန်ထမ်း၊ FDA၊ GMP နှင့် ကုန်အမှတ်တံဆိပ်ကို စစ်ဆေးပါ။", risk: "လက်ကားသို့မဟုတ် ထုပ်ပိုးထုတ်ကုန်များသည် လတ်ဆတ်ရောင်းချမှုနှင့် စည်းမျဉ်းကွာခြားသည်။" },
    hi: { title: "थाईलैंड में बेकरी कैसे खोलें", shortTitle: "बेकरी", summary: "ताज़ा खुदरा बिक्री और पैकेज्ड उत्पादन को अलग करें, फिर पंजीकरण, कर, FDA, GMP और ब्रांड जाँचें।", risk: "थोक या पैकेज्ड उत्पादन का दायरा ताज़ा काउंटर बिक्री से अलग है।" },
    zh: { title: "如何在泰国开面包店", shortTitle: "面包店", summary: "区分现做零售与预包装生产，再检查登记、税务、员工、泰国 FDA、GMP 及品牌事项。", risk: "批发或预包装生产与现做柜台销售的合规范围不同。" },
  } },
  { slug: "school", icon: "📚", tone: "blue", serviceSlugs: ["register-company", "business-plan-financial-model", "business-contract-review", "social-security", "monthly-accounting", "pdpa-starter", "trademark"], copy: {
    th: { title: "เปิดโรงเรียนเอกชนต้องขออนุญาตอะไร", shortTitle: "โรงเรียนเอกชน", summary: "แยกโรงเรียนในระบบและนอกระบบ ตรวจใบอนุญาต หลักสูตร อาคาร ผู้บริหาร ครู บุคลากร การเงิน และข้อมูลนักเรียนก่อนรับสมัคร", risk: "อย่าเช่าหรือดัดแปลงอาคารก่อนตรวจประเภทโรงเรียนและการใช้อาคารเพื่อการศึกษา เพราะขั้นตอนและคุณสมบัติต่างกัน" },
    en: { title: "How to open a private school in Thailand", shortTitle: "Private school", summary: "Identify whether the school is formal or non-formal, then check licensing, curriculum, premises, management, teachers, finance and student data before enrolment.", risk: "Do not lease or convert premises before confirming the school category and educational building-use requirements." },
    my: { title: "ထိုင်းနိုင်ငံတွင် ကိုယ်ပိုင်ကျောင်းဖွင့်ရန်", shortTitle: "ကိုယ်ပိုင်ကျောင်း", summary: "ကျောင်းအမျိုးအစား၊ လိုင်စင်၊ သင်ရိုး၊ အဆောက်အအုံ၊ စီမံခန့်ခွဲသူ၊ ဆရာ၊ ငွေကြေးနှင့် ကျောင်းသားအချက်အလက်ကို လက်ခံမတိုင်မီ စစ်ဆေးပါ။", risk: "ကျောင်းအမျိုးအစားနှင့် ပညာရေးအတွက် အဆောက်အအုံအသုံးပြုခွင့်ကို မစစ်မီ နေရာမငှားပါနှင့်။" },
    hi: { title: "थाईलैंड में निजी स्कूल कैसे खोलें", shortTitle: "निजी स्कूल", summary: "प्रवेश शुरू करने से पहले स्कूल प्रकार, लाइसेंस, पाठ्यक्रम, भवन, प्रबंधन, शिक्षक, वित्त और छात्र डेटा की जाँच करें।", risk: "स्कूल श्रेणी और शैक्षिक भवन उपयोग की पुष्टि से पहले परिसर किराये पर न लें।" },
    zh: { title: "如何在泰国开办私立学校", shortTitle: "私立学校", summary: "招生前确认学校类型，并检查许可、课程、场地、管理人员、教师、财务及学生数据要求。", risk: "确认学校类别及教育用途建筑要求前，不要先签租约或改造场地。" },
  } },
  { slug: "it-company", icon: "🏢", tone: "violet", serviceSlugs: ["register-company", "vat-registration", "monthly-accounting", "employment-contracts", "pdpa-starter", "trademark", "boi"], copy: {
    th: { title: "เปิดบริษัท IT ในไทยต้องเตรียมอะไร", shortTitle: "บริษัท IT", summary: "วางโครงสร้างบริษัท ภาษี สัญญาซอฟต์แวร์ ทรัพย์สินทางปัญญา ข้อมูลส่วนบุคคล ทีมงาน และตรวจใบอนุญาตเฉพาะตามบริการดิจิทัล", risk: "บริษัทซอฟต์แวร์ทั่วไปไม่มีใบอนุญาตกลางใบเดียว แต่บริการโทรคมนาคม Digital ID แพลตฟอร์ม การเงิน หรือธุรกิจต่างด้าวอาจมีกฎเฉพาะ" },
    en: { title: "How to start an IT company in Thailand", shortTitle: "IT company", summary: "Prepare the company, tax, software contracts, intellectual property, personal data, people and any sector licence triggered by the digital service.", risk: "General software development has no single industry licence, but telecoms, Digital ID, platforms, finance and foreign ownership can trigger specific rules." },
    my: { title: "ထိုင်းနိုင်ငံတွင် IT ကုမ္ပဏီဖွင့်ရန်", shortTitle: "IT ကုမ္ပဏီ", summary: "ကုမ္ပဏီ၊ အခွန်၊ ဆော့ဖ်ဝဲစာချုပ်၊ မူပိုင်ခွင့်၊ ကိုယ်ရေးဒေတာ၊ ဝန်ထမ်းနှင့် ဒစ်ဂျစ်တယ်ဝန်ဆောင်မှုအလိုက် လိုင်စင်ကို ပြင်ဆင်ပါ။", risk: "ပုံမှန်ဆော့ဖ်ဝဲဖွံ့ဖြိုးမှုအတွက် လိုင်စင်တစ်ခုမလိုသော်လည်း တယ်လီကွန်း၊ Digital ID၊ platform နှင့် ငွေကြေးဝန်ဆောင်မှုများတွင် အထူးစည်းမျဉ်းရှိနိုင်သည်။" },
    hi: { title: "थाईलैंड में IT कंपनी कैसे शुरू करें", shortTitle: "IT कंपनी", summary: "कंपनी, कर, सॉफ़्टवेयर अनुबंध, बौद्धिक संपदा, व्यक्तिगत डेटा, टीम और डिजिटल सेवा से जुड़े विशेष लाइसेंस तैयार करें।", risk: "सामान्य सॉफ़्टवेयर विकास के लिए एक केंद्रीय लाइसेंस नहीं है, लेकिन टेलीकॉम, Digital ID, प्लेटफ़ॉर्म और वित्तीय सेवाओं पर विशेष नियम लागू हो सकते हैं।" },
    zh: { title: "如何在泰国成立 IT 公司", shortTitle: "IT 公司", summary: "准备公司架构、税务、软件合同、知识产权、个人数据、团队及数字服务可能触发的专项许可。", risk: "一般软件开发没有统一行业许可证，但电信、Digital ID、平台、金融及外资业务可能适用专项规定。" },
  } },
  { slug: "pharmacy", icon: "💊", tone: "mint", serviceSlugs: ["register-company", "commercial-registration", "vat-registration", "social-security", "monthly-accounting", "fda-registration", "employment-contracts", "trademark"], copy: {
    th: { title: "เปิดร้านขายยาต้องมีใบอนุญาตอะไร", shortTitle: "ร้านขายยา", summary: "ตรวจใบอนุญาตขายยา ผู้รับอนุญาต เภสัชกรประจำร้าน มาตรฐาน GPP สถานที่ การเก็บยา บุคลากร ภาษี และสินค้าที่จะขาย", risk: "คำขอ ข.ย.1 ไม่ใช่ตัวใบอนุญาต ข้อมูลของ อย. แยกคำขอ ข.ย.1 และใบอนุญาตขายยาแผนปัจจุบันแบบ ข.ย.5" },
    en: { title: "How to open a pharmacy in Thailand", shortTitle: "Pharmacy", summary: "Check the drug-sale licence, licensee, pharmacist on duty, GPP, premises, storage, people, tax and the product scope before opening.", risk: "Form K.Y.1 is the application, while the Thai FDA lists the issued modern-drug sale licence separately as form K.Y.5." },
    my: { title: "ထိုင်းနိုင်ငံတွင် ဆေးဆိုင်ဖွင့်ရန်", shortTitle: "ဆေးဆိုင်", summary: "ဆေးရောင်းလိုင်စင်၊ လိုင်စင်ရသူ၊ တာဝန်ခံဆေးဝါးပညာရှင်၊ GPP၊ နေရာ၊ သိုလှောင်မှု၊ ဝန်ထမ်း၊ အခွန်နှင့် ကုန်ပစ္စည်းအမျိုးအစားကို စစ်ဆေးပါ။", risk: "ข.ย.1 သည် လျှောက်လွှာပုံစံဖြစ်ပြီး ထုတ်ပေးသော ခေတ်မီဆေးရောင်းလိုင်စင်ကို ข.ย.5 ဟု သီးခြားသတ်မှတ်ထားသည်။" },
    hi: { title: "थाईलैंड में फ़ार्मेसी कैसे खोलें", shortTitle: "फ़ार्मेसी", summary: "दवा बिक्री लाइसेंस, लाइसेंसधारी, ड्यूटी फ़ार्मासिस्ट, GPP, परिसर, भंडारण, कर्मचारी, कर और उत्पाद दायरे की जाँच करें।", risk: "K.Y.1 आवेदन प्रपत्र है; Thai FDA जारी आधुनिक दवा बिक्री लाइसेंस को अलग से K.Y.5 के रूप में सूचीबद्ध करता है।" },
    zh: { title: "如何在泰国开药店", shortTitle: "药店", summary: "开业前检查药品销售许可、持证人、驻店药师、GPP、场地、储存、人员、税务及商品范围。", risk: "ข.ย.1 是申请表，泰国 FDA 将正式现代药品销售许可证另列为 ข.ย.5。" },
  } },
  { slug: "pet-business", icon: "🐶", tone: "coral", serviceSlugs: ["register-company", "commercial-registration", "vat-registration", "social-security", "monthly-accounting", "import-export", "employment-contracts", "trademark"], copy: {
    th: { title: "เปิดธุรกิจสัตว์เลี้ยงต้องขออนุญาตอะไร", shortTitle: "ธุรกิจสัตว์เลี้ยง", summary: "แยกร้านขายสัตว์ คาเฟ่สัตว์ โรงแรมและกรูมมิ่ง คลินิกสัตว์ และนำเข้า–ส่งออก แล้วตรวจใบอนุญาตให้ตรงกับกิจกรรมจริง", risk: "ชื่อว่าธุรกิจสัตว์เลี้ยงยังไม่พอ ร้านขายสัตว์ คาเฟ่สัตว์ และสถานพยาบาลสัตว์อยู่ภายใต้กฎหมายและหน่วยงานคนละชุด" },
    en: { title: "How to start a pet business in Thailand", shortTitle: "Pet business", summary: "Separate animal sales, pet cafés, boarding and grooming, veterinary care, and import–export, then match each activity to its licence.", risk: "A pet-business label is not enough: animal trading, animal cafés and veterinary facilities are regulated under different regimes." },
    my: { title: "ထိုင်းနိုင်ငံတွင် အိမ်မွေးတိရစ္ဆာန်လုပ်ငန်းဖွင့်ရန်", shortTitle: "အိမ်မွေးတိရစ္ဆာန်လုပ်ငန်း", summary: "တိရစ္ဆာန်ရောင်းချမှု၊ pet café၊ တည်းခိုနှင့် grooming၊ တိရစ္ဆာန်ဆေးခန်း၊ တင်သွင်း–တင်ပို့ကို ခွဲပြီး လိုင်စင်ကိုက်ညီမှုစစ်ဆေးပါ။", risk: "တိရစ္ဆာန်ရောင်းခြင်း၊ pet café နှင့် တိရစ္ဆာန်ဆေးခန်းတို့သည် မတူသောဥပဒေများအောက်တွင်ရှိသည်။" },
    hi: { title: "थाईलैंड में पालतू पशु व्यवसाय कैसे शुरू करें", shortTitle: "पालतू पशु व्यवसाय", summary: "पशु बिक्री, पेट कैफ़े, बोर्डिंग व ग्रूमिंग, पशु चिकित्सा और आयात–निर्यात को अलग कर हर गतिविधि का लाइसेंस जाँचें।", risk: "पशु व्यापार, पेट कैफ़े और पशु चिकित्सा केंद्र अलग-अलग कानूनों के अधीन हैं।" },
    zh: { title: "如何在泰国开展宠物业务", shortTitle: "宠物业务", summary: "区分活体销售、宠物咖啡、寄养美容、动物诊疗及进出口，并按实际活动核对许可。", risk: "宠物销售、宠物咖啡和动物诊疗机构分别适用不同法规与主管部门。" },
  } },
];

export const industryUi: Record<LanguageCode, {
  nav: string; eyebrow: string; title: string; lead: string; explore: string; directoryTitle: string; directoryLead: string;
  quickTitle: string; checklistTitle: string; checklistLead: string; riskTitle: string; stepsTitle: string; documentsTitle: string;
  relatedTitle: string; faqTitle: string; ctaTitle: string; cta: string; taskCount: string; startingPrice: string; timeline: string;
  steps: string[]; documents: string[]; faqs: [string, string][];
}> = {
  th: { nav: "เริ่มตามธุรกิจ", eyebrow: "คู่มือตามประเภทธุรกิจ", title: "ธุรกิจของคุณ\nต้องเริ่มต่างกัน", lead: "เลือกประเภทกิจการ แล้วดูทะเบียน ภาษี ใบอนุญาต เอกสารและลำดับงานที่เกี่ยวข้องในหน้าเดียว", explore: "ดูแผนเริ่มธุรกิจ", directoryTitle: "เลือกคู่มือตามธุรกิจของคุณ", directoryLead: "14 แผนเริ่มกิจการยอดนิยม เชื่อมไปยังบริการและใบอนุญาตที่ต้องตรวจจริง", quickTitle: "คำตอบสั้นก่อนเริ่ม", checklistTitle: "งานที่ควรตรวจให้ครบ", checklistLead: "รายการด้านทะเบียน บัญชี ภาษี คน และใบอนุญาตที่มักเกี่ยวข้อง", riskTitle: "จุดที่ควรเช็กก่อนลงทุน", stepsTitle: "ลำดับเริ่มงาน", documentsTitle: "ข้อมูลที่ควรเตรียม", relatedTitle: "คู่มือธุรกิจอื่น", faqTitle: "คำถามก่อนเริ่ม", ctaTitle: "ให้ทีมช่วยเรียงลำดับตามกรณีของคุณ", cta: "รับแผนเริ่มต้น", taskCount: "งานที่เกี่ยวข้อง", startingPrice: "ราคาเริ่มต้น", timeline: "ระยะเวลา", steps: ["สรุปรูปแบบธุรกิจและสถานที่", "เลือกบุคคลธรรมดา ห้างหุ้นส่วน หรือบริษัท", "ตรวจใบอนุญาตก่อนเซ็นสัญญาสถานที่", "เตรียมทะเบียน ภาษี บัญชีและงานจ้าง", "ยื่นงานตามลำดับและเก็บหลักฐาน"], documents: ["รูปแบบรายได้และช่องทางขาย", "รายชื่อผู้ก่อตั้งหรือหุ้นส่วน", "ที่ตั้งและหลักฐานสิทธิใช้สถานที่", "รายละเอียดสินค้า บริการ เครื่องจักรหรืออุปกรณ์", "เป้าหมายเปิดให้บริการและงบประมาณ"], faqs: [["จำเป็นต้องจดบริษัททันทีไหม?", "ไม่เสมอไป ควรเทียบความเสี่ยง คู่ค้า รายได้ ใบอนุญาตและการรับผิดก่อนเลือกรูปแบบ"], ["เริ่มปรึกษาออนไลน์ได้หรือไม่?", "ได้ การสรุปข้อเท็จจริง รายการเอกสาร ร่างงานและอัปเดตสถานะส่วนใหญ่ทำได้ออนไลน์"], ["ราคาในหน้านี้เป็นราคาสุดท้ายหรือไม่?", "เป็นราคาเริ่มต้นของบริการแต่ละงาน ค่าราชการ ภาษี และค่าใช้จ่ายเฉพาะกรณีจะยืนยันแยกก่อนเริ่มงาน"]] },
  en: { nav: "Start by business", eyebrow: "Guides by business type", title: "Your business\nstarts differently", lead: "Choose an industry and see registrations, tax, licences, documents and the order of work in one place.", explore: "View launch plan", directoryTitle: "Choose a guide for your business", directoryLead: "Fourteen launch plans connected to the services and sector-specific licences to check in Thailand.", quickTitle: "The short answer", checklistTitle: "Workstreams to check", checklistLead: "Common registration, accounting, tax, people and licensing work for this business.", riskTitle: "Check before investing", stepsTitle: "Suggested sequence", documentsTitle: "Information to prepare", relatedTitle: "Other business guides", faqTitle: "Questions before starting", ctaTitle: "Get a plan matched to your facts", cta: "Get a starting plan", taskCount: "related workstreams", startingPrice: "Starting price", timeline: "Typical timeline", steps: ["Define the business model and premises", "Choose individual, partnership or company", "Check licences before committing to premises", "Prepare registration, tax, accounting and people work", "File in sequence and keep evidence"], documents: ["Revenue model and sales channels", "Founders or partners", "Premises and right-to-use evidence", "Products, services, machinery or equipment", "Target opening date and budget"], faqs: [["Must I form a company immediately?", "Not always. Compare risk, counterparties, income, licences and liability before choosing a structure."], ["Can the work start online?", "Yes. Fact gathering, checklists, drafts and most status updates can begin online."], ["Are the prices final?", "They are starting service prices. Government fees, VAT and case-specific costs are confirmed separately before work starts."]] },
  my: { nav: "လုပ်ငန်းအလိုက်စတင်ရန်", eyebrow: "လုပ်ငန်းအမျိုးအစားအလိုက် လမ်းညွှန်", title: "သင့်လုပ်ငန်းသည်\nမတူညီစွာစတင်သည်", lead: "လုပ်ငန်းအမျိုးအစားကိုရွေးပြီး မှတ်ပုံတင်၊ အခွန်၊ လိုင်စင်၊ စာရွက်စာတမ်းနှင့် အတင်းအစဉ်ကို တစ်နေရာတည်းတွင်ကြည့်ပါ။", explore: "စတင်မှုအစီအစဉ်ကိုကြည့်ရန်", directoryTitle: "သင့်လုပ်ငန်းအတွက် လမ်းညွှန်ရွေးပါ", directoryLead: "ထိုင်းနိုင်ငံတွင် စစ်ဆေးရမည့် ဝန်ဆောင်မှုများနှင့် လုပ်ငန်းအလိုက်လိုင်စင်များပါသော စတင်မှုအစီအစဉ် 14 ခု။", quickTitle: "အတိုချုပ်", checklistTitle: "စစ်ဆေးရန်အလုပ်များ", checklistLead: "မှတ်ပုံတင်၊ စာရင်းကိုင်၊ အခွန်၊ ဝန်ထမ်းနှင့် လိုင်စင်အလုပ်များ။", riskTitle: "ရင်းနှီးမှီ စစ်ဆေးပါ", stepsTitle: "အကြံပြုအစီအစဉ်", documentsTitle: "ပြင်ဆင်ရန်အချက်အလက်", relatedTitle: "အခြားလုပ်ငန်းလမ်းညွှန်", faqTitle: "မစတင်မီ မေးခွန်းများ", ctaTitle: "သင့်အခြေအနေနှင့်ကိုက်ညီသောအစီအစဉ်ရယူပါ", cta: "စတင်မှုအစီအစဉ်ရယူရန်", taskCount: "ဆက်စပ်အလုပ်များ", startingPrice: "စတင်စျေး", timeline: "ခန့်မှန်းအချိန်", steps: ["လုပ်ငန်းပုံစံနှင့် နေရာကိုသတ်မှတ်ပါ", "လုပ်ငန်းပုံစံကိုရွေးပါ", "နေရာစာချုပ်မလုပ်မီ လိုင်စင်စစ်ပါ", "မှတ်ပုံတင်၊ အခွန်၊ စာရင်းကိုင်နှင့် ဝန်ထမ်းအလုပ်ကိုပြင်ပါ", "အစီအစဉ်အတိုင်းလုပ်ပြီး အထောက်အထားများကိုသိမ်းပါ"], documents: ["ဝင်ငွေပုံစံနှင့် ရောင်းချျေးချောင်းများ", "တည်ထောင်သူများ", "နေရာနှင့် အသုံးပြုခွင့်အထောက်အထား", "ထုတ်ကုန်၊ ဝန်ဆောင်မှု၊ စက်ပစ္စည်းများ", "ဖွင့်မည့်ရက်နှင့် ခန့်မှန်းခြေငွေ"], faqs: [["ကုမ္ပဏီချက်ချင်းလိုသလား?", "မကြာခဏလိုသည်မဟုတ်ပါ။ အန္တရာယ်၊ ချိတ်ဆက်သူ၊ ဝင်ငွေ၊ လိုင်စင်နှင့် တာဝန်ယူမှုကိုနှိုင်းယှဉ်ပါ။"], ["အွန်လိုင်းမှစတင်နိုင်သလား?", "ရပါတယ်။ အခြေအနေစုဆောင်းခြင်း၊ စာရင်း၊ မူကြမ်းနှင့် အခြေအနေအပ်ဒိတ်များကို အွန်လိုင်းမှစနိုင်သည်။"], ["စျေးနှုန်းနောက်ဆုံးလား?", "အစဝန်ဆောင်ခသာဖြစ်သည်။ အစိုးရကြေး၊ VAT နှင့် အခြေအနေအလိုက်ကုန်ကျစရိတ်ကို ခွဲခြားအတည်ပြုမည်။"]] },
  hi: { nav: "व्यवसाय के अनुसार शुरू करें", eyebrow: "व्यवसाय प्रकार मार्गदर्शिका", title: "हर व्यवसाय\nअलग तरह शुरू होता है", lead: "उद्योग चुनें और पंजीकरण, कर, लाइसेंस, दस्तावेज़ और कार्य क्रम एक स्थान पर देखें।", explore: "शुरुआती योजना देखें", directoryTitle: "अपने व्यवसाय की मार्गदर्शिका चुनें", directoryLead: "थाईलैंड में जाँचने योग्य सेवाओं और क्षेत्र-विशिष्ट लाइसेंसों से जुड़ी 14 शुरुआती योजनाएँ।", quickTitle: "संक्षिप्त उत्तर", checklistTitle: "जाँचने वाले कार्य", checklistLead: "इस व्यवसाय के सामान्य पंजीकरण, लेखांकन, कर, कर्मचारी और लाइसेंस कार्य।", riskTitle: "निवेश से पहले जाँचें", stepsTitle: "सुझाया क्रम", documentsTitle: "तैयारी की जानकारी", relatedTitle: "अन्य व्यवसाय मार्गदर्शिका", faqTitle: "शुरू करने से पहले प्रश्न", ctaTitle: "अपने मामले के अनुसार योजना पाएँ", cta: "शुरुआती योजना पाएँ", taskCount: "संबंधित कार्य", startingPrice: "शुरुआती मूल्य", timeline: "अनुमानित समय", steps: ["व्यवाय मॉडल और स्थान तय करें", "व्यक्ति, साझेदारी या कंपनी चुनें", "स्थान लेने से पहले लाइसेंस जाँचें", "पंजीकरण, कर, लेखांकन और कर्मचारी कार्य तैयार करें", "क्रम में आवेदन करें और साक्ष्य रखें"], documents: ["राजस्व मॉडल और बिक्री चैनल", "संस्थापक या साझेदार", "स्थान और उपयोग अधिकार", "उत्पाद, सेवाएँ, मशीनरी या उपकरण", "लक्ष्य उद्घाटन तिथि और बजट"], faqs: [["क्या तुरंत कंपनी बनाना ज़रूरी है?", "हमेशा नहीं। संरचना चुनने से पहले जोखिम, भागीदार, आय, लाइसेंस और देयता की तुलना करें।"], ["क्या ऑनलाइन शुरू कर सकते हैं?", "हाँ। तथ्य संग्रह, चेकलिस्ट, मसौदे और स्थिति अपडेट ऑनलाइन शुरू हो सकते हैं।"], ["क्या कीमत अंतिम है?", "ये शुरुआती सेवा शुल्क हैं। सरकारी शुल्क, VAT और विशिष्ट लागत अलग पुष्ट की जाती है।"]] },
  zh: { nav: "按行业开始", eyebrow: "按行业分类指南", title: "不同业务\n有不同的起点", lead: "选择行业，在一个页面查看登记、税务、许可证、文件及办理顺序。", explore: "查看开业计划", directoryTitle: "选择您的行业指南", directoryLead: "14 个开业计划，连接在泰国应核查的服务及行业专项许可证。", quickTitle: "简要答案", checklistTitle: "需检查的事项", checklistLead: "该业务常见的登记、会计、税务、人事及许可工作。", riskTitle: "投资前请先检查", stepsTitle: "建议顺序", documentsTitle: "需准备的信息", relatedTitle: "其他行业指南", faqTitle: "开始前常见问题", ctaTitle: "获取符合实际情况的计划", cta: "获取起步计划", taskCount: "相关事项", startingPrice: "起步价", timeline: "预计时间", steps: ["明确业务模式与场地", "选择个人、合伙或公司", "签场地前先检查许可证", "准备登记、税务、会计与人事", "按顺序提交并保留证据"], documents: ["收入模式与销售渠道", "创始人或合伙人", "场地与使用权证明", "产品、服务、机械或设备", "目标开业日期与预算"], faqs: [["必须马上注册公司吗？", "不一定。选择结构前应比较风险、合作方、收入、许可证及责任。"], ["可以在线开始吗？", "可以。事实收集、清单、草稿及大多数进度更新均可在线开始。"], ["价格是最终价吗？", "页面为起步服务费。政府费、增值税及个案费用会在开始前单独确认。"]] },
};

export function industryDirectoryLead(locale: LanguageCode) {
  const count = industries.length;
  if (locale === "th") return `${count} แผนเริ่มกิจการ เชื่อมบริการและใบอนุญาตเฉพาะทางที่ต้องตรวจจริง`;
  if (locale === "en") return `${count} launch plans connecting services and sector-specific permits to check in Thailand.`;
  if (locale === "my") return `ထိုင်းနိုင်ငံတွင် စစ်ဆေးရမည့် ဝန်ဆောင်မှုနှင့် အထူးလိုင်စင်များကို ချိတ်ဆက်ထားသော စတင်မှုအစီအစဉ် ${count} ခု။`;
  if (locale === "hi") return `थाईलैंड में सेवाओं और विशेष लाइसेंस जाँच से जुड़ी ${count} शुरुआती योजनाएँ।`;
  return `${count} 个开业计划，连接在泰国需检查的服务与专项许可。`;
}

export function industryCopy(industry: Industry, locale: LanguageCode) { return industry.copy[locale]; }
export function getIndustry(slug: string) { return industries.find((industry) => industry.slug === slug); }
export function localeForIndustry(locale?: string): LanguageCode { return (locale === "en" || locale === "my" || locale === "hi" || locale === "zh") ? locale as Locale : "th"; }
