import type { Locale } from "@/lib/i18n";

type FaqPair = readonly [question: string, answer: string];

export const localizedFaqs: Record<Locale, readonly FaqPair[]> = {
  en: [
    ["Can a foreigner register a company in Thailand?", "Yes, a foreigner may invest in or establish a company in Thailand. The permitted ownership and operating structure depend on the business activity, the Foreign Business Act, sector rules and whether BOI promotion or another permission applies."],
    ["Can company registration in Thailand be completed online?", "Most planning, information collection, document review and status updates can be handled online. Some cases still require identity verification, original documents, signatures or an authority-specific step."],
    ["How many shareholders are required for a Thai limited company?", "The required number depends on the entity type and the rules in force on the filing date. Confirm the current DBD requirement before arranging shareholders, and never use a nominee who is not a genuine investor."],
    ["Can I use a home or condominium as a registered company address?", "It may be possible if the company has a valid right to use the premises and the building, lease, juristic-person rules and business licences allow it. VAT registration or regulated activities may require additional evidence and a suitable place of business."],
    ["Does registered capital have to be paid into a bank immediately?", "Registered capital, called-up capital and actual working cash are different concepts. Share payments should follow the corporate documents and be supported by reliable accounting and payment evidence."],
    ["Must a Thai company file tax returns and financial statements if it has no income?", "Generally, an incorporated company continues to have accounting, tax and annual filing duties even when it is inactive or has no revenue. Ignoring these duties can create penalties and make a later closure more difficult."],
    ["How should a foreign founder choose an accounting firm in Thailand?", "Compare the exact scope, filing calendar, document cut-off dates, named contact, language support, data security and charges outside the package. A low monthly fee is not useful unless the included work is clearly defined."],
    ["Should company documents be kept on paper or digitally?", "Use both formats where appropriate. Keep originals when required, and maintain a consistent digital folder structure, access permissions, file names and backups so records can be retrieved for tax, audit and corporate work."],
    ["When must a business register for VAT in Thailand?", "A business that regularly supplies taxable goods or services generally enters the VAT system when it meets the statutory turnover threshold; voluntary registration may also be possible. Check exemptions, timing and the current Revenue Department rules before acting."],
    ["After changing a director, which organisations should be notified?", "After the company record is updated, review signing authority and notify banks, payment platforms, key counterparties, tax and social-security offices, and any licensing authority that relies on director information."],
    ["Does a share transfer automatically update every government record?", "No. The transfer instrument, shareholder register and relevant corporate filings must be handled correctly, and tax consequences should be reviewed. Other licences, banks and contracts may also require separate updates."],
    ["Is moving a registered office to another province more complicated?", "It can involve additional resolutions, registration steps and coordination with tax, social-security and licensing offices. Plan the timeline before physically moving so invoices, signs and official records remain consistent."],
    ["How long does a capital increase in Thailand take?", "Timing depends on the entity, share structure, resolutions, subscription and payment evidence. The company should map the sequence before receiving funds and confirm any effect on foreign ownership or licences."],
    ["Is stopping business the same as dissolving a Thai company?", "No. Stopping sales does not end the legal entity or automatically remove filing duties. Formal dissolution and liquidation are required before the company is legally closed."],
    ["Does registering a company name protect the trademark?", "No. A company name and a trademark are separate systems. Search for similar marks and select the appropriate goods and service classes before relying on a brand name."],
    ["Does my business need a special licence before opening in Thailand?", "It depends on the activity, product, premises and location. Food, health products, clinics, factories, hotels, schools, recruitment, import-export and other regulated businesses may need approval before operating."],
    ["Do website prices include government fees and VAT?", "Displayed prices are starting service fees unless stated otherwise. A proper quotation should separate professional fees, government charges, VAT, certification, translation and third-party costs."],
    ["Can Tangton support a business located outside Bangkok?", "Yes. Consultation, preparation, draft review and status coordination can usually be handled online across Thailand. Any local inspection, original-document or in-person requirement will be identified before work begins."],
    ["How is information submitted through the consultation form used?", "It is used to assess scope, prepare a tailored document list and contact you about the requested service. Access, retention and deletion should follow the published privacy notice and applicable data-protection requirements."],
    ["What should I prepare for the first business consultation?", "Prepare your business activity, income model, founders or shareholders, proposed location, target opening date and any existing documents. You do not need a complete document set before the first discussion."],
  ],
  my: [
    ["နိုင်ငံခြားသားက ထိုင်းနိုင်ငံတွင် ကုမ္ပဏီမှတ်ပုံတင်နိုင်ပါသလား", "နိုင်ငံခြားသားသည် ထိုင်းနိုင်ငံတွင် ရင်းနှီးမြှုပ်နှံခြင်း သို့မဟုတ် ကုမ္ပဏီတည်ထောင်ခြင်း ပြုလုပ်နိုင်ပါသည်။ ပိုင်ဆိုင်မှုအချိုးနှင့် လုပ်ငန်းပုံစံသည် လုပ်ငန်းအမျိုးအစား၊ နိုင်ငံခြားသားလုပ်ငန်းဥပဒေ၊ သက်ဆိုင်ရာစည်းမျဉ်းနှင့် BOI ခွင့်ပြုချက်တို့အပေါ် မူတည်ပါသည်။"],
    ["ထိုင်းကုမ္ပဏီမှတ်ပုံတင်ခြင်းကို အွန်လိုင်းဖြင့် အပြီးလုပ်နိုင်ပါသလား", "အစီအစဉ်ချခြင်း၊ အချက်အလက်ပို့ခြင်း၊ စာရွက်စာတမ်းစစ်ဆေးခြင်းနှင့် အခြေအနေလိုက်ကြည့်ခြင်းကို အွန်လိုင်းဖြင့် အများစုလုပ်နိုင်ပါသည်။ အချို့ကိစ္စများတွင် မူရင်းစာရွက်စာတမ်း၊ လက်မှတ် သို့မဟုတ် ကိုယ်ရေးအတည်ပြုမှု လိုနိုင်ပါသည်။"],
    ["ထိုင်းလီမိတက်ကုမ္ပဏီအတွက် ရှယ်ယာရှင် ဘယ်နှယောက်လိုပါသလဲ", "လိုအပ်သည့်အရေအတွက်သည် လုပ်ငန်းပုံစံနှင့် တင်သွင်းသည့်နေ့တွင် အကျုံးဝင်သော DBD စည်းမျဉ်းအပေါ် မူတည်ပါသည်။ အမှန်တကယ်မရင်းနှီးမြှုပ်နှံသူကို နာမည်ခံရှယ်ယာရှင်အဖြစ် မသုံးသင့်ပါ။"],
    ["အိမ် သို့မဟုတ် ကွန်ဒိုကို ကုမ္ပဏီလိပ်စာအဖြစ် သုံးနိုင်ပါသလား", "နေရာအသုံးပြုခွင့်ရှိပြီး အဆောက်အအုံ၊ ငှားရမ်းစာချုပ်၊ စီမံခန့်ခွဲမှုစည်းမျဉ်းနှင့် လုပ်ငန်းလိုင်စင်တို့နှင့် မဆန့်ကျင်လျှင် ဖြစ်နိုင်ပါသည်။ VAT သို့မဟုတ် ထိန်းချုပ်ထားသောလုပ်ငန်းများအတွက် အထောက်အထားပိုလိုနိုင်ပါသည်။"],
    ["မှတ်ပုံတင်အရင်းအနှီးကို ဘဏ်ထဲ ချက်ချင်းထည့်ရပါသလား", "မှတ်ပုံတင်အရင်းအနှီး၊ ခေါ်ယူပေးသွင်းသည့်အရင်းအနှီးနှင့် လုပ်ငန်းသုံးငွေသည် မတူပါ။ ရှယ်ယာငွေပေးချေမှုကို ကုမ္ပဏီစာရွက်စာတမ်းနှင့် ကိုက်ညီစွာ လုပ်ပြီး ငွေပေးချေမှုအထောက်အထား ထားရှိသင့်ပါသည်။"],
    ["ဝင်ငွေမရှိသည့်ကုမ္ပဏီက အခွန်နှင့် ဘဏ္ဍာရေးရှင်းတမ်း တင်ရပါသလား", "ယေဘုယျအားဖြင့် ဝင်ငွေမရှိသော်လည်း နิติบุคคลတွင် စာရင်းကိုင်၊ အခွန်နှင့် နှစ်စဉ်တင်ပြရန်တာဝန် ရှိနေပါသည်။ မလုပ်ထားပါက ဒဏ်ကြေးနှင့် နောက်ပိုင်းပိတ်သိမ်းရာတွင် အခက်အခဲ ဖြစ်နိုင်ပါသည်။"],
    ["ထိုင်းနိုင်ငံတွင် စာရင်းကိုင်ရုံးကို ဘယ်လိုရွေးသင့်ပါသလဲ", "လုပ်ငန်းနယ်ပယ်၊ တင်သွင်းရက်စွဲ၊ စာရွက်စာတမ်းပို့ရမည့်ရက်၊ တာဝန်ခံသူ၊ ဘာသာစကားပံ့ပိုးမှု၊ ဒေတာလုံခြုံရေးနှင့် ပက်ကေ့ချ်ပြင်ပကုန်ကျစရိတ်တို့ကို နှိုင်းယှဉ်ပါ။"],
    ["ကုမ္ပဏီစာရွက်စာတမ်းကို စက္ကူနဲ့သိမ်းမလား ဒစ်ဂျစ်တယ်နဲ့သိမ်းမလား", "လိုအပ်သလို နှစ်မျိုးလုံးသုံးပါ။ မူရင်းလိုသည့်စာရွက်စာတမ်းကို ထိန်းသိမ်းပြီး ဖိုင်အမည်၊ ဖိုလ်ဒါ၊ ဝင်ရောက်ခွင့်နှင့် အရန်သိမ်းစနစ်ကို တိတိကျကျထားပါ။"],
    ["ထိုင်းနိုင်ငံတွင် VAT ဘယ်အချိန်မှတ်ပုံတင်ရပါသလဲ", "အခွန်ကျသင့်သည့်ကုန်ပစ္စည်း သို့မဟုတ် ဝန်ဆောင်မှုကို ပုံမှန်ရောင်းချပြီး ဥပဒေသတ်မှတ်ဝင်ငွေကို ရောက်သည့်အခါ VAT မှတ်ပုံတင်ရန် လိုတတ်ပါသည်။ ကင်းလွတ်ခွင့်နှင့် လက်ရှိ Revenue Department စည်းမျဉ်းကို အရင်စစ်ပါ။"],
    ["ဒါရိုက်တာပြောင်းပြီးနောက် ဘယ်အဖွဲ့အစည်းတွေကို အသိပေးရပါသလဲ", "ကုမ္ပဏီမှတ်တမ်းပြင်ပြီးနောက် လက်မှတ်ထိုးအာဏာကို စစ်ပြီး ဘဏ်၊ ငွေပေးချေမှုပလက်ဖောင်း၊ အရေးကြီးမိတ်ဖက်၊ အခွန်၊ လူမှုဖူလုံရေးနှင့် လိုင်စင်ဌာနများကို လိုအပ်သလို ပြင်ဆင်ပါ။"],
    ["ရှယ်ယာလွှဲပြောင်းလျှင် အစိုးရမှတ်တမ်းအားလုံး အလိုအလျောက်ပြောင်းပါသလား", "မပြောင်းပါ။ လွှဲပြောင်းစာချုပ်၊ ရှယ်ယာရှင်မှတ်ပုံတင်စာအုပ်၊ ကုမ္ပဏီတင်ပြချက်နှင့် အခွန်သက်ရောက်မှုကို သီးခြားစီ စီမံရပါသည်။"],
    ["မှတ်ပုံတင်ရုံးကို အခြားပြည်နယ်သို့ ပြောင်းခြင်း ပိုရှုပ်ထွေးပါသလား", "ဆုံးဖြတ်ချက်၊ မှတ်ပုံတင်အဆင့်နှင့် အခွန်၊ လူမှုဖူလုံရေး၊ လိုင်စင်ဌာနတို့နှင့် ဆက်စပ်လုပ်ဆောင်မှု ပိုရှိနိုင်ပါသည်။ အမှန်တကယ်မရွှေ့မီ အချိန်ဇယားပြုလုပ်ပါ။"],
    ["အရင်းအနှီးတိုးခြင်း ဘယ်လောက်ကြာပါသလဲ", "ကုမ္ပဏီပုံစံ၊ ရှယ်ယာဖွဲ့စည်းပုံ၊ ဆုံးဖြတ်ချက်၊ ရှယ်ယာဝယ်ယူမှုနှင့် ငွေပေးချေမှုအထောက်အထားအပေါ် မူတည်ပါသည်။ ငွေလက်ခံမီ အဆင့်လိုက်အစီအစဉ်ချထားသင့်ပါသည်။"],
    ["လုပ်ငန်းရပ်ခြင်းနဲ့ ကုမ္ပဏီဖျက်သိမ်းခြင်း တူပါသလား", "မတူပါ။ ရောင်းချမှုရပ်ထားရုံဖြင့် နิติบุคคล မပျက်သိမ်းသလို တင်ပြရန်တာဝန်လည်း မပျောက်ပါ။ တရားဝင်ပိတ်ရန် ဖျက်သိမ်းခြင်းနှင့် စာရင်းရှင်းလင်းခြင်း လုပ်ရပါသည်။"],
    ["ကုမ္ပဏီအမည်မှတ်ပုံတင်ခြင်းက ကုန်အမှတ်တံဆိပ်ကို ကာကွယ်ပါသလား", "မကာကွယ်ပါ။ ကုမ္ပဏီအမည်နှင့် ကုန်အမှတ်တံဆိပ်သည် သီးခြားစနစ်များဖြစ်ပြီး ဆင်တူတံဆိပ်ရှာဖွေမှုနှင့် သင့်တော်သည့် ကုန်ပစ္စည်း/ဝန်ဆောင်မှုအတန်းကို ရွေးရပါသည်။"],
    ["ထိုင်းနိုင်ငံတွင် လုပ်ငန်းမဖွင့်မီ အထူးလိုင်စင်လိုပါသလား", "လုပ်ငန်း၊ ထုတ်ကုန်၊ နေရာနှင့် တည်နေရာပေါ် မူတည်ပါသည်။ အစားအစာ၊ ကျန်းမာရေးထုတ်ကုန်၊ ဆေးခန်း၊ စက်ရုံ၊ ဟိုတယ်၊ ကျောင်းနှင့် သွင်းကုန်ပို့ကုန်လုပ်ငန်းများတွင် အထူးခွင့်ပြုချက် လိုနိုင်ပါသည်။"],
    ["ဝဘ်ဆိုက်ရှိဈေးနှုန်းတွင် အစိုးရကြေးနှင့် VAT ပါဝင်ပါသလား", "ရှင်းလင်းစွာ မဖော်ပြထားလျှင် ပြထားသည့်ဈေးသည် စတင်ဝန်ဆောင်ခ ဖြစ်ပါသည်။ ကိုးကားဈေးတွင် ဝန်ဆောင်ခ၊ အစိုးရကြေး၊ VAT၊ ဘာသာပြန်နှင့် ပြင်ပကုန်ကျစရိတ်ကို ခွဲပြသင့်ပါသည်။"],
    ["ဘန်ကောက်ပြင်ပက လုပ်ငန်းကို ဝန်ဆောင်မှုပေးနိုင်ပါသလား", "ရနိုင်ပါသည်။ ထိုင်းနိုင်ငံတစ်ဝန်း အကြံပေးခြင်း၊ စာရွက်စာတမ်းပြင်ဆင်ခြင်းနှင့် အခြေအနေလိုက်ကြည့်ခြင်းကို အွန်လိုင်းဖြင့် လုပ်နိုင်ပြီး ဒေသဆိုင်ရာလိုအပ်ချက်ကို အလုပ်မစမီ အသိပေးပါမည်။"],
    ["တိုင်ပင်ရေးဖောင်မှ ပို့သည့်အချက်အလက်ကို ဘာအတွက်သုံးပါသလဲ", "လုပ်ငန်းနယ်ပယ်အကဲဖြတ်ခြင်း၊ သီးသန့်စာရွက်စာတမ်းစာရင်းပြင်ဆင်ခြင်းနှင့် ပြန်လည်ဆက်သွယ်ခြင်းအတွက်သာ သုံးပါသည်။ သိမ်းဆည်းခြင်းနှင့် ဖျက်ခြင်းသည် ကိုယ်ရေးအချက်အလက်မူဝါဒအတိုင်း ဖြစ်သင့်ပါသည်။"],
    ["ပထမအကြိမ်တိုင်ပင်ရန် ဘာတွေပြင်ဆင်ရပါသလဲ", "လုပ်ငန်းအမျိုးအစား၊ ဝင်ငွေပုံစံ၊ ပါဝင်သူများ၊ ခန့်မှန်းတည်နေရာ၊ ဖွင့်လိုသည့်ရက်နှင့် ရှိပြီးသားစာရွက်စာတမ်းကို ပြင်ဆင်ပါ။ ပထမစကားပြောမီ စာရွက်စာတမ်းအပြည့်အစုံ မလိုပါ။"],
  ],
  hi: [
    ["क्या कोई विदेशी थाईलैंड में कंपनी पंजीकृत कर सकता है?", "हाँ। विदेशी व्यक्ति थाईलैंड में निवेश या कंपनी स्थापित कर सकता है। स्वामित्व और संचालन की अनुमति व्यवसाय की गतिविधि, Foreign Business Act, क्षेत्रीय नियमों और BOI या अन्य अनुमति पर निर्भर करती है।"],
    ["क्या थाईलैंड में कंपनी पंजीकरण पूरी तरह ऑनलाइन हो सकता है?", "योजना, जानकारी भेजना, दस्तावेज़ जाँच और स्थिति अपडेट सामान्यतः ऑनलाइन हो सकते हैं। कुछ मामलों में पहचान सत्यापन, मूल दस्तावेज़, हस्ताक्षर या विभाग-विशिष्ट प्रक्रिया आवश्यक हो सकती है।"],
    ["थाई लिमिटेड कंपनी के लिए कितने शेयरधारक चाहिए?", "संख्या संस्था के प्रकार और आवेदन के दिन लागू DBD नियमों पर निर्भर करती है। संरचना बनाने से पहले वर्तमान नियम जाँचें और ऐसे नाममात्र शेयरधारक का उपयोग न करें जो वास्तविक निवेशक नहीं है।"],
    ["क्या घर या कंडो को कंपनी का पंजीकृत पता बनाया जा सकता है?", "संभव हो सकता है यदि परिसर उपयोग करने का वैध अधिकार हो और भवन, लीज़, जुरिस्टिक-पर्सन नियम तथा लाइसेंस इसकी अनुमति दें। VAT या नियंत्रित व्यवसाय के लिए अतिरिक्त प्रमाण चाहिए हो सकते हैं।"],
    ["क्या पंजीकृत पूंजी तुरंत बैंक में जमा करनी होती है?", "पंजीकृत पूंजी, माँगी गई चुकता पूंजी और व्यवसाय की वास्तविक नकदी अलग बातें हैं। शेयर भुगतान कंपनी के दस्तावेज़ों के अनुसार करें और विश्वसनीय भुगतान व लेखांकन प्रमाण रखें।"],
    ["आय न होने पर भी कंपनी को टैक्स और वित्तीय विवरण दाखिल करने होते हैं?", "आमतौर पर हाँ। निष्क्रिय या बिना आय वाली कंपनी की भी लेखांकन, कर और वार्षिक फाइलिंग जिम्मेदारियाँ बनी रहती हैं। अनदेखी करने से जुर्माना और बाद में कंपनी बंद करने में कठिनाई हो सकती है।"],
    ["थाईलैंड में अकाउंटिंग फर्म कैसे चुनें?", "काम का स्पष्ट दायरा, फाइलिंग कैलेंडर, दस्तावेज़ की अंतिम तिथि, जिम्मेदार संपर्क, भाषा सहायता, डेटा सुरक्षा और पैकेज से बाहर के शुल्क की तुलना करें।"],
    ["कंपनी के दस्तावेज़ कागज़ पर रखें या डिजिटल रूप में?", "जहाँ उचित हो दोनों रखें। आवश्यक मूल दस्तावेज़ सुरक्षित रखें और डिजिटल फोल्डर, नामकरण, पहुँच अधिकार तथा बैकअप की व्यवस्थित व्यवस्था बनाएँ।"],
    ["थाईलैंड में VAT पंजीकरण कब आवश्यक होता है?", "करयोग्य वस्तुएँ या सेवाएँ नियमित रूप से बेचने वाला व्यवसाय कानूनी टर्नओवर सीमा पूरी होने पर सामान्यतः VAT प्रणाली में आता है। छूट, समय और Revenue Department के वर्तमान नियम पहले जाँचें।"],
    ["निदेशक बदलने के बाद किन संस्थाओं को सूचना देनी चाहिए?", "कंपनी रिकॉर्ड अपडेट होने के बाद हस्ताक्षर अधिकार जाँचें और बैंक, भुगतान प्लेटफॉर्म, प्रमुख ग्राहक, कर व सामाजिक सुरक्षा कार्यालय और संबंधित लाइसेंस विभाग को आवश्यकतानुसार अपडेट करें।"],
    ["क्या शेयर ट्रांसफर से सभी सरकारी रिकॉर्ड अपने आप बदल जाते हैं?", "नहीं। ट्रांसफर दस्तावेज़, शेयरधारक रजिस्टर, संबंधित कंपनी फाइलिंग और कर प्रभाव अलग से संभालने पड़ते हैं। बैंक, लाइसेंस और अनुबंध भी अपडेट माँग सकते हैं।"],
    ["दूसरे प्रांत में पंजीकृत कार्यालय ले जाना अधिक जटिल है?", "इसमें अतिरिक्त प्रस्ताव, पंजीकरण और कर, सामाजिक सुरक्षा तथा लाइसेंस कार्यालयों के साथ समन्वय हो सकता है। वास्तविक स्थानांतरण से पहले समयरेखा बनाना बेहतर है।"],
    ["थाईलैंड में पूंजी बढ़ाने में कितना समय लगता है?", "समय कंपनी के प्रकार, शेयर संरचना, प्रस्ताव, सदस्यता और भुगतान प्रमाण पर निर्भर करता है। धन लेने से पहले क्रम तय करें और विदेशी स्वामित्व या लाइसेंस पर प्रभाव जाँचें।"],
    ["व्यवसाय रोकना और कंपनी बंद करना क्या एक ही बात है?", "नहीं। बिक्री रोकने से कानूनी संस्था समाप्त नहीं होती और फाइलिंग जिम्मेदारियाँ भी स्वतः खत्म नहीं होतीं। कानूनी समापन के लिए विघटन और परिसमापन आवश्यक है।"],
    ["क्या कंपनी का नाम पंजीकृत करने से ट्रेडमार्क सुरक्षित हो जाता है?", "नहीं। कंपनी नाम और ट्रेडमार्क अलग प्रणालियाँ हैं। ब्रांड पर भरोसा करने से पहले समान ट्रेडमार्क खोजें और सही वस्तु व सेवा वर्ग चुनें।"],
    ["क्या थाईलैंड में व्यवसाय खोलने से पहले विशेष लाइसेंस चाहिए?", "यह गतिविधि, उत्पाद, परिसर और स्थान पर निर्भर करता है। भोजन, स्वास्थ्य उत्पाद, क्लिनिक, फैक्टरी, होटल, स्कूल, भर्ती और आयात-निर्यात जैसे व्यवसायों को विशेष अनुमति चाहिए हो सकती है।"],
    ["क्या वेबसाइट की कीमत में सरकारी शुल्क और VAT शामिल हैं?", "स्पष्ट रूप से लिखे बिना दिखाई गई कीमत शुरुआती सेवा शुल्क है। कोटेशन में पेशेवर शुल्क, सरकारी शुल्क, VAT, प्रमाणन, अनुवाद और तीसरे पक्ष की लागत अलग दिखाई जानी चाहिए।"],
    ["क्या बैंकॉक के बाहर स्थित व्यवसाय को सेवा मिल सकती है?", "हाँ। परामर्श, तैयारी, मसौदा समीक्षा और स्थिति समन्वय थाईलैंड भर में ऑनलाइन हो सकता है। स्थानीय निरीक्षण या व्यक्तिगत उपस्थिति की आवश्यकता काम शुरू होने से पहले बताई जाएगी।"],
    ["परामर्श फॉर्म से भेजी जानकारी का उपयोग कैसे होता है?", "जानकारी का उपयोग दायरा समझने, व्यक्तिगत दस्तावेज़ सूची तैयार करने और आपसे संपर्क करने के लिए होता है। पहुँच, भंडारण और हटाने की प्रक्रिया प्रकाशित गोपनीयता नीति के अनुसार होनी चाहिए।"],
    ["पहली व्यावसायिक सलाह के लिए क्या तैयार करें?", "व्यवसाय की गतिविधि, आय मॉडल, संस्थापक या शेयरधारक, प्रस्तावित स्थान, शुरू करने की तारीख और उपलब्ध दस्तावेज़ तैयार रखें। पहली बातचीत से पहले पूरा दस्तावेज़ सेट आवश्यक नहीं है।"],
  ],
  zh: [
    ["外国人可以在泰国注册公司吗？", "可以。外国人可在泰国投资或设立公司，但持股比例和经营方式取决于具体业务、外国人经商法、行业规定，以及是否适用 BOI 投资促进或其他许可。"],
    ["泰国公司注册可以全部在线完成吗？", "前期咨询、资料收集、文件审查和进度跟踪大多可以在线完成。部分个案仍可能需要身份核验、文件原件、签字或主管机关指定的线下步骤。"],
    ["泰国有限公司需要多少名股东？", "所需人数取决于企业类型及提交申请当日有效的 DBD 规定。安排股东结构前应确认最新要求，不应使用并非真实投资人的名义股东。"],
    ["住宅或公寓可以作为泰国公司注册地址吗？", "如公司有合法使用权，且不违反楼宇、租约、物业管理规定和相关许可证，通常有可能使用。申请 VAT 或经营受监管业务时，可能需要额外场地证明。"],
    ["注册资本必须立即存入公司银行账户吗？", "注册资本、催缴资本和企业实际营运资金是不同概念。股款支付应与公司决议和文件一致，并保留可靠的付款及会计凭证。"],
    ["泰国公司没有收入也需要报税和提交财务报表吗？", "通常仍需要。即使公司暂未经营或没有收入，仍可能负有会计、税务和年度申报义务。长期不处理可能产生罚款，并增加后续注销难度。"],
    ["外国创业者应如何选择泰国会计事务所？", "应比较明确的服务范围、申报日历、资料截止日、固定联系人、语言支持、数据安全，以及套餐外收费。不能只比较月费。"],
    ["公司文件应保存纸质版还是电子版？", "应按文件类型同时规划。需要原件的文件应妥善保存，电子资料则应统一文件名、文件夹、访问权限和备份方式，便于税务、审计及公司事务调用。"],
    ["在泰国什么时候必须登记 VAT？", "持续销售应税商品或提供应税服务的经营者，达到法定营业额门槛时通常需要登记 VAT。办理前应确认豁免情形、申报时限及泰国税务局最新规定。"],
    ["变更董事后需要通知哪些机构？", "公司登记更新后，应检查签字权限，并按需要更新银行、支付平台、主要合作方、税务局、社会保障办公室及使用董事资料的许可证主管机关。"],
    ["股权转让后所有政府记录会自动更新吗？", "不会。需要正确处理转让文件、股东名册、相关公司申报及税务影响；银行、许可证和合同也可能需要分别更新。"],
    ["将注册地址迁往其他府会更复杂吗？", "可能需要额外的股东或董事决议、登记步骤，并与税务、社会保障和许可证机关协调。实际搬迁前应先规划时间表。"],
    ["泰国公司增资通常需要多长时间？", "时间取决于公司类型、股权结构、决议、认购和付款凭证。收款前应先确定步骤，并检查是否影响外资比例或行业许可证。"],
    ["暂停营业等于注销泰国公司吗？", "不等于。停止销售不会使法人自动终止，申报义务也不会自动消失。公司需完成正式解散和清算程序后才算依法关闭。"],
    ["注册公司名称能同时保护商标吗？", "不能。公司名称与商标属于不同制度。正式使用品牌前，应检索近似商标并选择正确的商品和服务类别。"],
    ["在泰国开业前需要申请特殊许可证吗？", "取决于业务、产品、场所和所在地。食品、健康产品、诊所、工厂、酒店、学校、招聘和进出口等受监管业务可能需要在营业前取得许可。"],
    ["网站价格是否包含政府规费和 VAT？", "除非页面明确说明，否则所列价格为起步服务费。正式报价应分别列出专业服务费、政府规费、VAT、认证、翻译及第三方费用。"],
    ["曼谷以外的企业也可以获得服务吗？", "可以。咨询、资料准备、文件审查和进度协调通常可在泰国全境在线进行。如需当地检查、原件或本人到场，会在开始前说明。"],
    ["咨询表中提交的资料会如何使用？", "资料用于评估服务范围、准备个案文件清单及联系回复。访问权限、保存期限和删除方式应遵循网站公布的隐私政策及适用的数据保护规定。"],
    ["第一次企业咨询需要准备什么？", "可先准备业务活动、收入模式、创始人或股东、拟用地址、计划开业日期及现有文件。首次沟通前无需备齐全部资料。"],
  ],
};
