"use client";

import { useMemo, useState } from "react";
import { dict, type Locale } from "@/lib/i18n";

const numberFormat = (locale: Locale, value: number) => value.toLocaleString(locale === "zh" ? "zh-CN" : locale === "my" ? "my-MM" : locale === "hi" ? "hi-IN" : "en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function LocalizedToolbox({ locale }: { locale: Locale }) {
  const t = dict(locale).tools;
  const [amount, setAmount] = useState("10000"); const [rate, setRate] = useState("7"); const [inclusive, setInclusive] = useState(false);
  const [salary, setSalary] = useState("25000"); const [people, setPeople] = useState("3"); const [ssoRate, setSsoRate] = useState("5"); const [cap, setCap] = useState("15000");
  const [founders, setFounders] = useState("one"); const [liability, setLiability] = useState("low");
  const vat = useMemo(() => { const n = Math.max(0, Number(amount.replaceAll(",", "")) || 0); const r = Math.max(0, Number(rate) || 0) / 100; return inclusive ? { base: n / (1 + r), vat: n - n / (1 + r), total: n } : { base: n, vat: n * r, total: n * (1 + r) }; }, [amount, rate, inclusive]);
  const employee = useMemo(() => { const wage = Math.max(0, Number(salary.replaceAll(",", "")) || 0); const count = Math.max(1, Math.round(Number(people) || 1)); const contribution = Math.min(wage, Math.max(0, Number(cap) || 0)) * (Math.max(0, Number(ssoRate) || 0) / 100); return { payroll: wage * count, contribution: contribution * count, cost: (wage + contribution) * count }; }, [salary, people, ssoRate, cap]);
  const result = liability === "separate" ? t.resultCompany : founders === "many" ? t.resultPartnership : t.resultSolo;
  return <div className="toolbox-grid toolbox-v2 localized-toolbox">
    <section className="tool-card tool-wide" data-testid="localized-vat"><div className="tool-head"><span>01</span><div><h2>{t.vatTitle}</h2><p>{t.note}</p></div></div><div className="tool-two-columns"><div className="tool-controls"><label>{t.amount}<input aria-label={t.amount} inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>{t.rate}<input aria-label={t.rate} inputMode="decimal" value={rate} onChange={(event) => setRate(event.target.value)} /></label><div className="segmented"><button type="button" className={!inclusive ? "active" : ""} onClick={() => setInclusive(false)}>{t.exclusive}</button><button type="button" className={inclusive ? "active" : ""} onClick={() => setInclusive(true)}>{t.inclusive}</button></div></div><dl className="vat-result"><div><dt>{t.base}</dt><dd>{numberFormat(locale, vat.base)}</dd></div><div><dt>{t.vat}</dt><dd data-testid="localized-vat-amount">{numberFormat(locale, vat.vat)}</dd></div><div><dt>{t.total}</dt><dd>{numberFormat(locale, vat.total)}</dd></div></dl></div></section>
    <section className="tool-card" data-testid="localized-employee"><div className="tool-head"><span>02</span><div><h2>{t.employeeTitle}</h2><p>{t.note}</p></div></div><div className="compact-fields"><label>{t.salary}<input aria-label={t.salary} value={salary} onChange={(event) => setSalary(event.target.value)} /></label><label>{t.people}<input aria-label={t.people} value={people} onChange={(event) => setPeople(event.target.value)} /></label><label>{t.ssoRate}<input aria-label={t.ssoRate} value={ssoRate} onChange={(event) => setSsoRate(event.target.value)} /></label><label>{t.cap}<input aria-label={t.cap} value={cap} onChange={(event) => setCap(event.target.value)} /></label></div><dl className="cost-result"><div><dt>{t.payroll}</dt><dd>{numberFormat(locale, employee.payroll)}</dd></div><div><dt>{t.contribution}</dt><dd>{numberFormat(locale, employee.contribution)}</dd></div><div><dt>{t.cost}</dt><dd>{numberFormat(locale, employee.cost)}</dd></div></dl></section>
    <section className="tool-card recommender" data-testid="localized-structure"><div className="tool-head"><span>03</span><div><h2>{t.structureTitle}</h2><p>{t.note}</p></div></div><label>{t.founders}<select aria-label={t.founders} value={founders} onChange={(event) => setFounders(event.target.value)}><option value="one">{t.one}</option><option value="many">{t.many}</option></select></label><label>{t.liability}<select aria-label={t.liability} value={liability} onChange={(event) => setLiability(event.target.value)}><option value="low">{t.low}</option><option value="separate">{t.separate}</option></select></label><div className="recommendation-result"><span>{t.result}</span><h3 data-testid="localized-structure-result">{result}</h3><p>{t.note}</p></div></section>
  </div>;
}
