import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { HubFooter, HubHeader } from "@/components/HubHeader";
import { Breadcrumbs, ConsultationCta, JsonLd } from "@/components/SeoBlocks";
import { languageAlternates } from "@/lib/i18n";
import { getServiceContent } from "@/lib/service-content";
import { serviceIcon, serviceImage } from "@/lib/service-visuals";
import { categoryInfo, getService, serviceFaqs, services, siteUrl } from "@/lib/site-data";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return services.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const service = getService((await params).slug); if (!service) return {};
  return { title: `${service.title} ราคา ขั้นตอน และเอกสาร`, description: `${service.summary} ราคาเริ่มต้น ${service.price} ใช้เวลา ${service.time} ดูขั้นตอน เอกสาร และคำถามที่พบบ่อย`, keywords: service.keywords, alternates: { canonical: `/services/${service.slug}`, languages: languageAlternates(`/services/${service.slug}`) }, openGraph: { title: `${service.title} | ตั้งต้น`, description: service.summary, url: `/services/${service.slug}`, images: ["/og.png"] } };
}

export default async function ServicePage({ params }: Props) {
  const service = getService((await params).slug); if (!service) notFound();
  const content = getServiceContent(service); const faqs = [...content.faqs, ...serviceFaqs(service)]; const category = categoryInfo[service.category];
  const related = services.filter((item) => item.category === service.category && item.slug !== service.slug).slice(0, 3);
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "Service", name: service.title, description: service.summary, provider: { "@type": "ProfessionalService", name: "ตั้งต้น", url: siteUrl }, areaServed: { "@type": "Country", name: "ประเทศไทย" }, offers: { "@type": "Offer", priceCurrency: "THB", description: `ค่าบริการเริ่มต้น ${service.price}` } },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "หน้าหลัก", item: siteUrl }, { "@type": "ListItem", position: 2, name: "บริการ", item: `${siteUrl}/services` }, { "@type": "ListItem", position: 3, name: service.title, item: `${siteUrl}/services/${service.slug}` }] },
    { "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.q, acceptedAnswer: { "@type": "Answer", text: faq.a } })) },
  ] };
  return <><HubHeader path={`/services/${service.slug}`} /><main className="inner-main"><JsonLd data={schema} />
    <section className={`service-hero service-hero-v3 ${category.accent}`}><div className="container"><Breadcrumbs items={[{ label: "หน้าหลัก", href: "/" }, { label: "บริการ", href: "/services" }, { label: service.title }]} /><div className="service-hero-grid"><div className="service-hero-copy"><div className="service-title-row"><span className="service-hero-icon" aria-hidden="true">{serviceIcon(service.slug, service.category)}</span><p className="eyebrow"><span /> {service.category}</p></div><h1>{service.title}<br /><em>เห็นราคา เวลา และรายละเอียดก่อนเริ่ม</em></h1><p>{service.summary}</p><div className="service-quick-pills"><span>✓ รายการส่งมอบเฉพาะงาน</span><span>✓ เอกสารพร้อมคำอธิบาย</span><span>✓ ขั้นตอนและจุดเสี่ยงครบ</span></div><div className="hero-actions"><Link className="button button-primary" href="/#contact">ประเมินกรณีของคุณ <span aria-hidden="true">↗</span></Link><a className="button button-ghost" href="#overview">ดูข้อมูลก่อนตัดสินใจ</a></div></div><aside className="service-hero-panel"><figure><img src={serviceImage(service.slug, service.category)} alt={`ภาพประกอบบริการ${service.title}`} width="1280" height="720" loading="eager" decoding="async" fetchPriority="high" /><span aria-hidden="true">{serviceIcon(service.slug, service.category)}</span><figcaption><small>{content.profile}</small><strong>{service.title}</strong></figcaption></figure><div className="service-fact-card"><div className="fact-card-title"><span>สรุปก่อนเริ่ม</span><b>ข้อมูลเบื้องต้น</b></div><dl><div><dt>ราคาเริ่มต้น</dt><dd>{service.price}</dd></div><div><dt>เวลาดำเนินการ</dt><dd>{service.time}</dd></div><div><dt>รูปแบบบริการ</dt><dd>ออนไลน์ทั่วไทย</dd></div></dl><small>* ยืนยันราคาและกรอบเวลาอีกครั้งหลังตรวจเอกสารจริง</small></div></aside></div></div></section>
    <nav className="service-jump-nav" aria-label="หัวข้อในหน้า"><div className="container"><a href="#overview">ภาพรวม</a><a href="#documents">เอกสาร</a><a href="#steps">ขั้นตอน</a><a href="#risks">ข้อควรระวัง</a><a href="#service-faq">คำถามพบบ่อย</a></div></nav>
    <section className="service-detail" id="details"><div className="container service-content-grid"><article className="longform">
      <section className="service-content-card" id="overview" data-reveal><div className="content-card-head"><span>01</span><div><small>ภาพรวมและสิ่งที่จะได้รับ</small><h2>{service.title} ช่วยจัดการอะไรให้ธุรกิจ?</h2></div></div><p className="content-lead">{content.overview}</p><p>เหมาะสำหรับ{service.audience} โดยจะยืนยันขอบเขตจากเอกสารและข้อเท็จจริงก่อนเริ่มทุกครั้ง</p><div className="service-deliverables">{content.outcomes.map((item, index) => <div key={item.title}><span aria-hidden="true">{["◎", "⌕", "✓"][index]}</span><strong>{item.title}</strong><p>{item.text}</p></div>)}</div></section>
      <section className="service-content-card" id="documents" data-reveal><div className="content-card-head"><span>02</span><div><small>เช็กลิสต์พร้อมเหตุผล</small><h2>เอกสารที่ใช้ และใช้เพื่ออะไร</h2></div></div><div className="document-list document-list-detailed">{content.documents.map((doc, index) => <div key={doc.title}><i>{String(index + 1).padStart(2, "0")}</i><span><strong>{doc.title}</strong><small>{doc.text}</small></span><b aria-hidden="true">✓</b></div>)}</div><div className="note-box"><span aria-hidden="true">i</span><div><strong>ยังไม่ครบก็เริ่มประเมินได้</strong><p>ส่งสิ่งที่มีมาให้ตรวจ แล้วรับรายการเอกสารเฉพาะกรณี พร้อมระบุว่าอะไรใช้สำเนา อะไรต้องใช้ต้นฉบับหรือยืนยันเพิ่ม</p></div></div></section>
      <section className="service-content-card" id="steps" data-reveal><div className="content-card-head"><span>03</span><div><small>กระบวนการพร้อมผลลัพธ์</small><h2>5 ขั้นตอนจากเริ่มจนส่งมอบ</h2></div></div><ol className="step-list step-list-detailed">{content.steps.map((step, index) => <li key={step.title}><span>{index + 1}</span><div><small>{index === 0 ? "เริ่มต้น" : index === 4 ? "ส่งมอบ" : `ขั้นที่ ${index + 1}`}</small><strong>{step.title}</strong><p>{step.text}</p><b>ผลลัพธ์: {step.output}</b></div></li>)}</ol><div className="time-summary"><span>⌛</span><div><small>เวลาดำเนินการโดยประมาณ</small><strong>{service.time}</strong></div><p>เริ่มนับเมื่อข้อมูลที่จำเป็นพร้อม โดยจะแจ้งจุดรออนุมัติหรือหน่วยงานแยกจากเวลาที่ทีมดำเนินการ</p></div></section>
      <section className="service-content-card" id="risks" data-reveal><div className="content-card-head"><span>04</span><div><small>ตรวจก่อนเริ่ม</small><h2>จุดเสี่ยงเฉพาะงาน {service.title}</h2></div></div><div className="risk-grid">{[...content.risks, { title: "ข้อมูลหลายเวอร์ชัน", text: "กำหนดผู้ยืนยันข้อมูลและชุดเอกสารหลักก่อนดำเนินการทุกครั้ง" }, { title: "ไม่วางงานที่เชื่อมต่อ", text: "ตรวจผลกระทบต่อบัญชี ภาษี คน สัญญา และใบอนุญาตหลังส่งมอบ" }].map((item, index) => <div key={item.title}><span>{["!", "↔", "≠", "✓"][index]}</span><strong>{item.title}</strong><p>{item.text}</p></div>)}</div></section>
      <section className="service-content-card" id="service-faq" data-reveal><div className="content-card-head"><span>05</span><div><small>คำถาม–คำตอบ</small><h2>คำตอบก่อนเริ่ม {service.title}</h2></div></div><div className="faq-list compact">{faqs.map((faq, index) => <details key={faq.q} open={index === 0}><summary><span>{faq.q}</span><i aria-hidden="true">+</i></summary><p>{faq.a}</p></details>)}</div></section>
    </article><aside className="service-side"><div className="side-card service-price-side"><span>ราคาเริ่มต้น</span><strong>{service.price}</strong><small>เวลาโดยประมาณ {service.time}</small><Link href="/#contact">ขอประเมินราคา <b aria-hidden="true">↗</b></Link></div><div className="side-card"><span>เหมาะกับ</span><p>{service.audience}</p></div><div className="side-card plain"><strong>บริการที่เกี่ยวข้อง</strong>{related.map((item) => <Link href={`/services/${item.slug}`} key={item.slug}><span aria-hidden="true">{serviceIcon(item.slug, item.category)}</span>{item.title}<b aria-hidden="true">→</b></Link>)}</div></aside></div></section>
    <section className="related-section"><div className="container"><div className="mini-heading"><span>ทำต่อได้ทันที</span><h2>บริการในกลุ่มเดียวกัน</h2></div><div className="related-grid">{related.map((item) => <Link href={`/services/${item.slug}`} key={item.slug}><span>{item.category}</span><h3>{item.title}</h3><p>{item.summary}</p><b>ดูรายละเอียด ↗</b></Link>)}</div><ConsultationCta title={`ต้องการประเมิน ${service.title} จากกรณีจริง?`} /></div></section>
  </main><HubFooter /></>;
}
