import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/SeoBlocks";
import ConsultationForm from "@/components/ConsultationForm";
import { LocalizedFooter, LocalizedHeader } from "@/components/LocalizedShell";
import { industries, industryCopy, industryUi } from "@/lib/industry-data";
import { categoryKey, dict, isLocale, languageAlternates, localizedPath, localizedServiceTitle, locales, type CategoryKey, type Locale } from "@/lib/i18n";
import { services, siteUrl } from "@/lib/site-data";

type Props = { params: Promise<{ locale: string }> };
const keys: CategoryKey[] = ["start", "finance", "people", "change", "licenses"];
const tones: Record<CategoryKey, string> = { start: "mint", finance: "sand", people: "violet", change: "blue", licenses: "rose" };

export function generateStaticParams() { return locales.map((locale) => ({ locale })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params; if (!isLocale(locale)) return {};
  const t = dict(locale); const url = `${siteUrl}/${locale}`;
  return { title: { absolute: `${t.brand} — ${t.hero.line1} ${t.hero.line2} ${t.hero.accent}` }, description: t.hero.lead, alternates: { canonical: url, languages: languageAlternates() }, openGraph: { title: `${t.brand} — ${t.hero.line1} ${t.hero.accent}`, description: t.hero.lead, url, locale: t.htmlLang, images: ["/og.png"] } };
}

export default async function LocalizedHome({ params }: Props) {
  const { locale: raw } = await params; if (!isLocale(raw)) notFound(); const locale: Locale = raw; const t = dict(locale); const p = (path = "") => localizedPath(locale, path);
  const categoryCards = keys.map((key, index) => ({ key, number: String(index + 1).padStart(2, "0"), count: services.filter((service) => categoryKey(service.category) === key).length, ...t.category[key], tone: tones[key] }));
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "ProfessionalService", name: t.brand, url: `${siteUrl}/${locale}`, description: t.hero.lead, areaServed: { "@type": "Country", name: "Thailand" }, availableLanguage: ["Thai", "English", "Burmese", "Hindi", "Simplified Chinese"] }, { "@type": "WebSite", name: t.brand, url: `${siteUrl}/${locale}`, inLanguage: t.htmlLang }] };
  return <><JsonLd data={schema} /><LocalizedHeader locale={locale} />
    <main lang={t.htmlLang}>
      <section className="hero hero-v2 localized-hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span /> {t.hero.eyebrow}</p><h1>{t.hero.line1}<br />{t.hero.line2}<br /><em>{t.hero.accent}</em></h1><p className="hero-lead">{t.hero.lead}</p><div className="hero-actions"><Link className="button button-primary" href="#contact">{t.hero.primary} <span aria-hidden="true">↗</span></Link><Link className="button button-ghost" href={p("/services")}>{t.hero.secondary}</Link></div><div className="hero-proof">{t.proof.map(([title, detail]) => <div key={title}><strong>{title}</strong><span>{detail}</span></div>)}</div></div>
      <div className="business-board"><div className="board-head"><span className="live-dot" /> {t.hero.board}<b>{t.hero.ready}</b></div><div className="board-score"><div><small>{t.hero.board}</small><strong>{t.hero.ready}</strong></div><span>5/5</span></div><div className="board-track"><i /></div><div className="board-rows">{categoryCards.map((item) => <div key={item.key}><span className={item.tone}>{item.number}</span><div><strong>{item.title}</strong><small>{item.count} {t.directory.count}</small></div><b>✓</b></div>)}</div><Link href={p("/services")}>{t.section.services} <span aria-hidden="true">↗</span></Link></div></div>
      <div className="container category-ribbon">{categoryCards.map((item) => <Link href={`${p("/services")}#${item.key}`} key={item.key}><span>{item.number}</span>{item.title}</Link>)}</div></section>

      <section className="section category-atlas"><div className="container"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> {t.section.eyebrow}</p><h2>{t.section.title}</h2></div><div className="section-copy"><p>{t.section.lead}</p><Link className="text-link" href={p("/services")}>{t.section.services} <span aria-hidden="true">↗</span></Link></div></div><div className="atlas-grid">{categoryCards.map((item) => <article className={`atlas-card ${item.tone}`} key={item.key}><div className="atlas-top"><span>{item.number}</span><small>{item.count} {t.directory.count}</small></div><h3>{item.title}</h3><p>{item.intro}</p><div className="localized-service-samples">{services.filter((service) => categoryKey(service.category) === item.key).slice(0, 3).map((service) => <span key={service.slug}>✓ {localizedServiceTitle(locale, service.slug)}</span>)}</div><Link href={`${p("/services")}#${item.key}`}>{t.section.services} <span aria-hidden="true">↗</span></Link></article>)}</div></div></section>

      <section className="section industry-home"><div className="container"><div className="section-heading split-heading" data-reveal><div><p className="eyebrow"><span /> {industryUi[locale].eyebrow}</p><h2>{industryUi[locale].title.split("\n").map((line, index) => <span key={line}>{line}{index === 0 && <br />}</span>)}</h2></div><div className="section-copy"><p>{industryUi[locale].lead}</p><Link className="text-link" href={p("/business-guides")}>{industryUi[locale].directoryTitle} <span aria-hidden="true">↗</span></Link></div></div><div className="industry-grid compact">{industries.map((industry, index) => { const copy = industryCopy(industry, locale); return <Link className={`industry-card ${industry.tone}`} href={p(`/business-guides/${industry.slug}`)} key={industry.slug} data-reveal style={{ "--reveal-delay": `${Math.min(index % 5, 4) * 60}ms` } as React.CSSProperties}><span className="industry-icon" aria-hidden="true">{industry.icon}</span><small>{industry.serviceSlugs.length} {industryUi[locale].taskCount}</small><h3>{copy.shortTitle}</h3><p>{copy.title}</p><b>{industryUi[locale].explore} <span aria-hidden="true">↗</span></b></Link>; })}</div></div></section>

      <section className="answer-section content-proof"><div className="container content-proof-grid"><div><p className="eyebrow light"><span /> {t.section.contentEyebrow}</p><h2>{t.section.contentTitle}</h2><p>{t.section.contentLead}</p><div className="content-stats"><div><strong>40</strong><span>{t.directory.count}</span></div><div><strong>5</strong><span>{t.section.eyebrow}</span></div><div><strong>5</strong><span>{t.language}</span></div></div></div><div className="language-showcase">{[{code:"TH",label:"ไทย"},{code:"EN",label:"English"},{code:"MY",label:"မြန်မာ"},{code:"HI",label:"हिन्दी"},{code:"中文",label:"简体中文"}].map((item) => <div key={item.code}><span>{item.code}</span><strong>{item.label}</strong><small>SEO • hreflang • localized content</small></div>)}</div></div></section>

      <section className="section tools-preview"><div className="container tools-preview-grid"><div className="tools-preview-copy"><p className="eyebrow"><span /> {t.section.toolsEyebrow}</p><h2>{t.section.toolsTitle}</h2><p>{t.section.toolsLead}</p><ul><li><span className="check">✓</span>{t.tools.vatTitle}</li><li><span className="check">✓</span>{t.tools.employeeTitle}</li><li><span className="check">✓</span>{t.tools.structureTitle}</li></ul><Link className="button button-primary" href={p("/tools")}>{t.section.toolsCta} <span aria-hidden="true">↗</span></Link></div><div className="tool-demo-card"><div className="tool-demo-head"><span>VAT 7%</span><small>{t.tools.vatTitle}</small></div><div className="tool-demo-input"><span>{t.tools.base}</span><strong>10,000.00</strong></div><div className="tool-demo-result"><div><span>{t.tools.vat}</span><strong>700.00</strong></div><div><span>{t.tools.total}</span><strong>10,700.00</strong></div></div><div className="tool-demo-foot"><span>{t.tools.note}</span><Link href={p("/tools")}>→</Link></div></div></div></section>

      <section className="contact-section localized-contact" id="contact"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow light"><span /> {t.consult}</p><h2>{t.section.ctaTitle}</h2><p>{t.section.ctaLead}</p><figure className="contact-visual"><img src="/illustration-consultation-v7.webp" alt="" width="1280" height="720" loading="lazy" decoding="async" /></figure><div className="contact-assurance"><div><span className="check">✓</span><span><strong>{t.section.contentTitle}</strong><small>{t.section.contentLead}</small></span></div><div><span className="check">✓</span><span><strong>{t.section.toolsTitle}</strong><small>{t.section.toolsLead}</small></span></div></div></div><ConsultationForm locale={locale} /></div></section>
    </main><LocalizedFooter locale={locale} /></>;
}
